### ISSUE TITLE
Des avis disparaissent du tableau de la liste des avis d'une démarche lorsqu'on trie sur la colonne "verbatim"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1004]
https://us02web.zoom.us/rec/share/0RjDMfJbr3bAr9kRDyZ8IM3cuGmuPDTc6eklC17bDMDKLIm1xORWkckvawaE261g.i6BlT9rZskOf7gag 
(Code secret: mail à @lucaa )

**Comment by AnthonyBrunelli** [comment]
Dans le tableau des avis, le nombre total des avis change lorsqu'on tri sur colonne certains critères, cf. vidéo.
Piste: bug lorsque le tri se fait sur des critères sur la page 2 du formulaire JDMA, or les saisies de la page 2 sont moins nombreux que ceux de la page 1. Point d'attention: il reste dans la liste des cas où tous les champs de la page 2 sont vides, mais peut-être parce que la page 2 a été validée vide...

**Comment by AnthonyBrunelli** [comment]
@lucaa tu peux passer cette issue en confidentiel stp? Je ne sais pas comment on fait.

**Comment by lucaa** [comment]
> @lucaa tu peux passer cette issue en confidentiel stp? Je ne sais pas comment on fait.

Ce n'est pas possible sur github, la fonctionnalité n'existe pas: https://github.community/t/when-will-we-finally-get-confidential-issues-for-security-tickets/124703 (et nombreuses autres références sur internet).

Pourquoi est-ce nécessaire, ceci ne semble pas décrire un problème de sécurité... On peut communiquer par email les informations privées par rapport au cas d'usage et laisser ici, sur le ticket public, uniquement la description du problème.

**Comment by AnthonyBrunelli** [comment]
Données perso sur la vidéo, Kheira y apparait, on voit des verbatims. Du coup, je t'ia transmis le mot de passe par mail.

**Comment by AnthonyBrunelli** [comment]
@lucaa Tu aurais des éléments sur ce sujet? C'est pour savoir quelle valeur donner aux chiffres, on a des analyses en cours...

**Comment by lucaa** [comment]
Alors, les avis qui disparaissent de la liste sont des avis pour lesquels la deuxième page n'a pas été validée _du tout_ (vide ou pas). 

Ce sont, donc, des avis pour lesquels on n'a qu'une partie de l'information, on n'a rien pour toutes les réponses de la deuxième page et techniquement on ne peut pas les inclure dans le tri. Ce comportement va arriver pour toutes les colonnes qui sont des informations optionnelles de l'avis.
Je dois vérifier si on peut corriger avec le stockage courant des avis, ou si on doit attendre l'amélioration du stockage des avis pour corriger ce problème. 

Note: la différence entre 8502 et 8506 est liée au fait qu'il y a un cache sur la page de synthèse des avis, la donnée date du matin de la journée en question (d'ou la différence avec le tableau des avis qui, lui, est parfaitement "en direct").

**Comment by AnthonyBrunelli** [comment]
Super, merci Anca!
Si tu as une analyse technique ou des scénarios, on est preneur. Pas d'urgence à ce stade, mais il faudra penser aux utilisateurs dans les ministères et donc prendre une décision sur le sujet.

**Comment by lucaa** [comment]
En terme de correctif, une solution peut être de ne pas offrir la possibilité de trier par ces colonnes, pour empêcher de se retrouver dans une situation incompréhensible, et laisser uniquement les options de filtrage.

Pour aider à prendre cette décision, il faudrait comprendre à quel but est utilisé le tri. Si je comprends bien la video, pour ce cas là, le tri est utilisé comme un filtre, pour obtenir tous les avis ayant un verbatim, tel que décrit dans #917 , donc il vaut mieux implémenter un vrai filtre.

**Comment by lucaa** [comment]
> Note: la différence entre 8502 et 8506 est liée au fait qu'il y a un cache sur la page de synthèse des avis, la donnée date du matin de la journée en question (d'ou la différence avec le tableau des avis qui, lui, est parfaitement "en direct").

Pour cette différence il y aussi un autre aspect à prendre en compte, en + du cache:

Contrairement aux graphes, la liste des avis n'affiche pas les avis _de l'année_ , mais tous les avis enregistrés pour cette démarche de toutes les années. 

Cette différence faisait partie des aspects de l'implémentation de l'année glissante que j'ai listé dans le ticket #748 . J'ai discuté ce cas avec @georges-bayard au téléphone et la décision a été que cela ne représente pas un problème car la période des avis est clairement expliquée dans l'onglet des graphes (voir https://github.com/DISIC/wikidemarches/issues/748#issuecomment-569085416 ). Effectivement, le fait que la période n'est pas clairement expliquée dans l'onglet de la liste des avis est un aspect qui peut être amélioré.

**Comment by raphj** [comment]
Le travail lié à la tâche #1194 devrait résoudre ce problème: la nouvelle manière de stocker les propriétés et de faire des requête sur les avis fait que si des champs sont vides, cela ne pose plus de problème lors de l'utilisation de ces filtres.
