### ISSUE TITLE
Bug mail automatique création d'un nouveau compte

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1020]
Nous avons reçu des dizaines (centaines?) de fois un mail de création de nouveau compte (vous êtes a priori en copie du côté de XWiki...). C'est les russes?

**Comment by AnthonyBrunelli** [comment]
![image](https://user-images.githubusercontent.com/35567048/130638905-6ddd7319-11ee-45e1-a5c7-b043af291f76.png)

**Comment by AnthonyBrunelli** [comment]
Au passage: où paramétrer la liste des destinataires de ce mail svp?

**Comment by AnthonyBrunelli** [comment]
@slauriere : salut, me suis permis de te taguer car il me semble que Ludovic et Anca sont en vacances? (j'espère que je ne te dérange pas pendant les tiennes...)

**Comment by AnthonyBrunelli** [comment]
J'ai tenté une suppression du compte dans l'interface admin. On va voir si ça marche.

**Comment by slauriere** [comment]
Salut Anthony, Bien reçu, je suis en train de regarder !

**Comment by AnthonyBrunelli** [comment]
Merci @slauriere ! Ma tentative n'a servi à rien... Normalement, je l'ai sorti de la base utilisateur (que tu saches si tu cherches, en tout cas j'ai essayé), sans effet.

**Comment by slauriere** [comment]
Je pense que la suppression du compte a quand même permis de stopper les envois et que là nous ne recevons plus que les mails envoyés envoyés avant la suppression : dans les logs du serveur je vois que l'URL de validation du compte était appelée en boucle plusieurs fois par minute, et ce n'est plus le cas à présent. Ça n'explique pas toutefois ce qui s'est passé, cela nécessitera une investigation.

Les destinataires du mail actuellement sont tous les membres du groupe XWikiAdminGroup.

**Comment by AnthonyBrunelli** [comment]
Ok merci !

**Comment by slauriere** [comment]
J'ajoute pour mémo ci-dessous un extrait du log Tomcat qui fait apparaître l'appel en boucle de l'URL de validation (en masquant la clef de validation et l'identifiant utilisateur) : 

```
2021-08-24 16:52:20,659 [https://observatoire.numerique.gouv.fr/XWiki/AccountValidation?validkey=XXX&xwikiname=YYY] WARN  o.x.v.i.DefaultVelocityEngine  - Deprecated usage of method [com.xpn.xwiki.XWiki.getClass] in 362:xwiki:XWiki.AccountValidation@28,42 
2021-08-24 16:52:36,801 [https://observatoire.numerique.gouv.fr/XWiki/AccountValidation?validkey=XXX&xwikiname=YYY] WARN  o.x.v.i.DefaultVelocityEngine  - Deprecated usage of method [com.xpn.xwiki.XWiki.getClass] in 255:xwiki:XWiki.AccountValidation@28,42 
2021-08-24 16:52:53,019 [https://observatoire.numerique.gouv.fr/XWiki/AccountValidation?validkey=XXX&xwikiname=YYY] WARN  o.x.v.i.DefaultVelocityEngine  - Deprecated usage of method [com.xpn.xwiki.XWiki.getClass] in 438:xwiki:XWiki.AccountValidation@28,42 
```

**Comment by AnthonyBrunelli** [comment]
Daté et non reproduit, je ferme.

**Comment by lucaa** [comment]
On a vu une situation similaire depuis, que j'ai traité et @slauriere m'a signalé comme étant la même que celle décrite par ce ticket.

Mon analyse lors du traitement de cette nouvelle situation et la suivante:
* le processus courant d'inscription fait qu'un email est envoyé à l'admin à chaque fois que l'utilisateur "confirme" son adresse email par l'URL reçue dans son email, même si cela a été déjà cliqué une fois
* ainsi, si un utilisateur cliqué / accède à l'URL de confirmation de son compte plusieurs fois, plusieurs emails sont envoyé
* il peut y avoir des cas légitimes des utilisateurs qui confirment leur email plusieurs fois pour plusieurs raisons (manque d'attention aux messages pour comprendre qu'il y a une étape supplémentaire de validation, etc.).
* j'imagine qu'il pourrait aussi y avoir des cas illégitimes où des comptes sont créés automatiquement par des robots qui peuvent passer la protection anti-robot de la page d'inscription et ensuite accéder au lien de validation de compte en boucle, ainsi générant des emails pour les admins
  * d'un point de vue sécurité ce passage de la protection anti-robot reste mineur car le compte n'étant pas encore activé, il n'a pas accès à grande chose, le seul problème peut être lié aux emails en boucle.

Comme tout ce processus d'inscription sera revu pour #1104 , on prendra en compte aussi l'aspect de l'email multiple. Ainsi, je confirme la fermeture de ce ticket.
