### ISSUE TITLE
Question: API pour extraire des données du back de l’Observatoire

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1026]
Question d'un collègue dont je crois connaître la réponse mais ocazou:
"vous savez si on a une API pour extraire des données du back de l’Observatoire ou c’est enfermé dedans?
L’idée étant d’injecter dans l’annuaire Airtable de l’Observatoire pour éviter les copier-coller et autres désynchronisations qui vont avec…"

**Comment by lucaa** [comment]
Réponse: des APIs génériques XWiki existent pour obtenir toutes les informations stockées dans XWiki. Par contre, ces APIs peuvent s’avérer inefficaces pour obtenir les informations des avis, à la fois pour des raisons de performance mais aussi pour des raisons de spécialisation de cette API.

Ticket #1200 a été créé pour ajouter une API métier pour obtenir les informations agrégés des avis, à base des données agrégées mises en place pour #1129, pour assurer la performance.

Je ferme cette tâche, comme une question répondue.
