### ISSUE TITLE
Porteur de démarche : supprimer le fil d'Ariane

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1035]
Le fil d'Ariane ne correspond pas au parcours + peu de pages concernent le profil porteur + accès à des pages et des menus difficilement compréhensible

Donc on masque/supprime.

**Comment by lucaa** [comment]
Je pense que c'est plus cohérent d'éteindre cela à tous les profils qui ne sont pas des administrateurs Dinum.

**Comment by AnthonyBrunelli** [comment]
Oui effectivement!

**Comment by lucaa** [comment]
C'est fait, le fil d'Ariane est désormais affiché uniquement aux administrateurs globaux (administrateurs Dinum).

**Comment by ugodtn** [comment]
@AnthonyBrunelli  vous avez testé, non ?

**Comment by AnthonyBrunelli** [comment]
Oui c'est bon ! :)
