### ISSUE TITLE
Mise en place de la page de présentation du produit JDMA

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1048]
![non-connecté (version sans avis)](https://user-images.githubusercontent.com/657716/158178027-3caf7ac7-7996-4904-a2c3-8e2fe687c524.jpg)

extrait du mockup sur figma: https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=514%3A49335

Notes:
* les composants dsfr doivent être inclus sur cette page, comme sur le formulaire d'avis, pour rendre facile la mise en place des différents éléments de la page (qui sont principalement des éléments dsfr mais pas uniquement)
* Le lien "Commencer" pointe vers: 
  * le formulaire d'inscription pour l'utilisateur non-connecté (voir tâche #1056 )
  * le formulaire d'ajout de nouvelle démarche pour les utilisateurs connectés - à valider par @ugodtn .
* html pur à prévoir dans l'implémentation, pour rendre cette page facilement éditable.
* la section de FAQ en bas de la page est un élément DSFR et devrait être, si possible, isolé dans une page séparée pour pouvoir facilement modifier les éléments du FAQ par les admins dinum. Il faut, néanmoins, considérer que tout élément de cette page pourrait être modifié par les admins dinum.
* la section "Elles recommandent" visible sur Figma n'est pas encore prête à implémenter, une tâche séparée va être créé pour cela.

Les liens vers cette page seront mis en place sur la page d'accueil et dans le header, dans le cadre de cette tâche.

**Comment by AnthonyBrunelli** [comment]
"Le lien "Commencer" pointe vers le formulaire d'ajout de nouvelle démarche pour les utilisateurs connectés - à valider par @ugodtn " :  non, on arrive vers la page d'accueil connectée de l'utilisateur.

Ok sur le reste. [note: vu avec Kale et Ugo]

**Comment by kamalcon** [comment]
![Frame 25](https://user-images.githubusercontent.com/14159449/162958939-ca72380c-9c2c-4666-8455-f49bf07485e0.svg)
![Frame 26](https://user-images.githubusercontent.com/14159449/162958943-fa826202-4cf2-4045-ae7b-b02f9d00ae79.svg)
![Frame 27](https://user-images.githubusercontent.com/14159449/162958948-06927444-d994-4b21-8d06-51b154b646e2.svg)
![Frame 28](https://user-images.githubusercontent.com/14159449/162958950-1b10e8d9-6b08-4807-ad0f-fa777cceb824.svg)
@ClemDee voici les svgs, n'hésites pas si tu a besoin d'autres

**Comment by ClemDee** [comment]
> @ClemDee voici les svgs, n'hésites pas si tu a besoin d'autres

Super merci ! Justement j'ai mis un autre comentaire sur figma, j'aurais juste besoin en plus de la toute première image de la page : 
![image](https://user-images.githubusercontent.com/45625842/162985314-09a10e87-8101-41cf-9d62-9ec903474b80.png)

**Comment by kamalcon** [comment]
Cela j'en ai pas en format vectoriel, c'est Ugo qui l’a créé dans Sketch. Mais je l’ai en PNG / SVG non-vectoriel 
![image 7](https://user-images.githubusercontent.com/14159449/162986480-2c7d4976-5ef2-4ae1-8a4b-c0ec11398311.png)
![image 7](https://user-images.githubusercontent.com/14159449/162986486-32968b08-69e2-46bf-9baa-f91e4d9d1794.svg)
:

**Comment by ClemDee** [comment]
> Cela j'en ai pas en format vectoriel, c'est Ugo qui l’a créé dans Sketch. Mais je l’ai en PNG / SVG non-vectoriel

Pas grave ça fera l'affaire merci :+1:

**Comment by ClemDee** [comment]
Travail effectué : 
 * Implémentation du design de la page de présentation du produit JDMA
 * Mise à jour des liens du header et de la page d'accueil
 * Mise à jour d'une image de l'accueil pour utiliser une pièce jointe de la page JDMA
 
La section FAQ a été implémentée dans une page à part : `JDMA.FAQ`, et contient une macro `{{html}}` permettant d'inserer du markup dsfr pour l'affichage des accordéons question/réponse.

Puisqu'il n'y avait pas de maquette sur figma pour l'affichage de cette page en format mobile, j'ai essayé de prendre des choix cohérents avec les autres layouts prévu pour cette taille d'affichage, mais il y aura peut-être des marges ou tailles d'éléments à revoir.

**Comment by lucaa** [comment]
> Puisqu'il n'y avait pas de maquette sur figma pour l'affichage de cette page en format mobile, j'ai essayé de prendre des choix cohérents avec les autres layouts prévu pour cette taille d'affichage, mais il y aura peut-être des marges ou tailles d'éléments à revoir.

Je pense que j'ai enfin compris le principe des liens / permaliens des ressources de figma. La version mobile **est présente** sur figma, mais pas à l'endroit ou pointe le lien de la description de ce ticket, dans la zone "non-connectée" : https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=577%3A50340 .

Je rouvre le ticket pour vérifier l'implémentation par rapport aux mockups de figma,

**Comment by lucaa** [comment]
À re-vérifier aussi par rapport à la maquette figma: les tailles de polices des différentes sections de la page, avec le ratio 16px = 1em. Il y a au moins le texte explicatif de la première section qui ne correspond pas.
D'ailleurs, pour la première section l'image est aussi placée différemment de la maquette.

**Comment by ClemDee** [comment]
- Mise à jour de la taille de police
- mise à jour du contenu de la page FAQ (et mise à jour en tant que page non-upgradable)
- mise à jour de styles par rapport aux maquettes

**Comment by lucaa** [comment]
> On a changé les couleurs de ces deux images afin de les harmoniser avec les couleurs du design systeme ![Frame 23](https://user-images.githubusercontent.com/14159449/167603692-c370341a-52d9-4dd7-b973-6c7aeeb2cabb.svg) ![Frame 88](https://user-images.githubusercontent.com/14159449/167603700-bdddc719-7da3-43f2-a069-da7f1270d6e3.svg)

J'ai créé un nouveau ticket pour cette modification #1125, pour ne pas rouvrir celui ci (pour ne pas risquer de le garder ouvert à l'infini car le travail a été fini).
