### ISSUE TITLE
[DSFR] Implémentation du footer du site DSFR compatible

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1050]
Dans l'objectif d'implémenter le DSFR partout, en attendant une intégration complète du DSFR, il faudrait appliquer les principes du DSFR au footer du site.

Normalement ce travail a déjà été fait dans #1006, cette tâche est pour vérifier la complétude de ce travail, par rapport au mockup ici: extrait du mockup sur figma: https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=49%3A26243 .

**Comment by lucaa** [comment]
à re-voir après implémentation du #1061 .

**Comment by lucaa** [comment]
@ClemDee dans cette tâche il s'agit principalement des vérifications que le footer correspond aux dessins de figma, s'il y a des différences, validons ensemble avant d'implémenter.

**Comment by ClemDee** [comment]
Petits fix du footer pour le rendre conforme aux dsfr : 
- maj de la couleur des séparateurs (vers un gris plus clair)
- maj des marges du séparateur horizontal
