### ISSUE TITLE
Implémentation de la nouvelle page d'accueil (décoration et réagencement des liens)

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1052]
Accueil non-connecté:

![image](https://user-images.githubusercontent.com/657716/157707662-209a2f0f-fdc2-4c0a-9070-06ecd08dd441.png)

extrait du mockup sur figma: https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=540%3A51476 .

Le comportement du mobile est également sur Figma.

Les décorations dsfr de base devraient être hérités du thème créé pour la tâche #1051 .

à faire: tout, sauf les icônes des sections des indicateurs de qualité, qui sont encore à définir (dans le cadre de #1086 - il faut laisser les icônes courantes, pour l'instant), y compris:
* couleurs des boutons et styles
* couleurs de fond d'écran
* mise à jour des textes.

@ugodtn: il faudra nous fournir l'image pour la section "Vous êtes porteur ou porteuse... ".

Le lien "en savoir plus" de la zone "Comment evaluons-nous la qualité..." reste le même qu'aujourd'hui, le lien "en savoir plus" de la section "Vous êtes porteur ou porteuse..." pointe vers la nouvelle page décrite par #1048 .

L'affichage de la section pour l'utilisateur connecté est à traiter par #1053 , pour l'instant laisser les 2 sections connectées une en dessous de l'autre et assurer uniquement le mode non-connecté pour cette tâche.

**Comment by lucaa** [comment]
@ugodtn: il faudra nous fournir l'image pour la section "Vous êtes porteur ou porteuse... ".

L'image peut être obtenue par export de Figma, la voilà ici: ![Frame 23](https://user-images.githubusercontent.com/657716/157858919-f23f26f1-c354-4bd7-acdf-94de7a21a0d5.svg)

Question(s) posées sur Figma pour clarifier les règles d'affichage de cette section et de la section en dessus.

**Comment by ClemDee** [comment]
Mise à jour de la page d'accueil aux nouvelles maquettes :
* Mise à jour des styles des éléments
* Mise à jour des marges entre les élements (mobile & desktop)
* Mise à jour des textes

**Comment by lucaa** [comment]
J'ai ajouté quelques commentaires sur le commit b2d4c85 , je rouvre pour regarder ces éléments.

aussi @ClemDee : il y a des conversations sur le placement et les tailles des éléments sur le mockup Figma, dans l'outil de conversation de figma, avec plusieurs clarifications. As-tu accès à ces informations, peux-tu intégrer ces informations-là dans l'implémentation, stp? Thanks!

**Comment by ClemDee** [comment]
> J'ai ajouté quelques commentaires sur le commit [b2d4c85](https://github.com/DISIC/observatoire/commit/b2d4c85ec1f50cc1432bdec43b3e706ca5d13a8c) , je rouvre pour regarder ces éléments.

Oui j'y ai répondu, tout est fixé.

> aussi @ClemDee : il y a des conversations sur le placement et les tailles des éléments sur le mockup Figma, dans l'outil de conversation de figma, avec plusieurs clarifications. As-tu accès à ces informations, peux-tu intégrer ces informations-là dans l'implémentation, stp? Thanks!

En effet j'ai accès à ces informations, je les ai déjà prises en compte dans l'implémentation.

**Comment by ClemDee** [comment]
Mise à jour depuis réouverture : 
- mise à jour des breakpoints bootstrap pour correspondre aux breakpoints dsfr
- les boutons prennent désormais 100% de la largeur en affichage "mobile"
- suppression de code commenté qui n'était plus utilisé pour l'accueil

**Comment by AnthonyBrunelli** [comment]
- Les icônes ont été ajoutés sur les maquettes;
- " il faudra nous fournir l'image pour la section "Vous êtes porteur ou porteuse... " " -> c'est disponible dans Figma (si problème, à voir avec @kamalcon

Vu ok [note: vu avec Ugo & Kale]
