### ISSUE TITLE
Implémentation de la page d'accueil pour l'utilisateur connecté (nouvelle section et modification de section)

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1053]
Les outils sensibles au rôle de l'utilisateur courant de la page d'accueil doivent être mis à jour ainsi:
* Déplacer la zone des outils pour le mode connecté uniquement en dessous de la séction de présentation de l'observatoire - plus d'outils en bas de la page

Pour tout utilisateur connecté, l'écran à obtenir est le suivant:
![aucune demarche](https://user-images.githubusercontent.com/657716/158074907-ef79528a-5303-4e72-8cbb-46f97bb68657.jpg)
Modifications à faire, par rapport à l'ecran de la page d'accueil non-connectée décrite dans #1052:
* La section "Vous êtes porteur ou porteuse..." n'est plus affiché du tout;
* L'explication de l'observatoire ainsi que le bouton pour consulter l'observatoire ne sont plus affichés dans la première section de l'écran;
* La section bleue "Comment évaluons-nous" la qualité est modifiée ainsi:
  * le titre change mais le texte d'explication reste le même;
  * le bouton pour accéder à l'observatoire est déplacé ici (depuis la première section);
  * le bouton "En savoir plus" devient "En savoir plus sur les indicateurs" mais pointe vers la même page.

Les outils d'accès aux démarches portées change de la manière courante, par rapport à la version aujourd'hui en production (4.9):
* la recherche est isolée dans une section dédiée et re-décorée mais garde son fonctionnement;
* la liste des démarches portées est affichée dans une nouvelle section, avec un bouton pour créer une nouvelle démarche - ce bouton est le bouton affiché aujourd'hui dans la page de recherche (ou à la fin de la liste de résultats rapides de recherche);
  * Le lien "comment ça marche" pointe vers la page de présentation du bouton, décrite dans #1048;
  * La vue avec une liste des démarches portées est la suivante - voir ci-dessus l'écran pour la vue sans démarche portée: ![image](https://user-images.githubusercontent.com/657716/158075220-88b7f1a9-7e1f-42d2-9996-77f485c104e7.png)
    * Le bouton "installer l'outil ..." est couvert par la tâche #1054 , donc pas traité ici
    
Pour les autres rôles (non spécifiés dans les mockups figma) - administrateur ministeriel et admin dinum:
* ajouter une nouvelle section en dessous de la section "mes démarches" avec les boutons d'accès aux outils et proposer une section plus compacte pour ces outils.

Mockup complet sur figma https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=90%3A24913 .

**Comment by AnthonyBrunelli** [comment]
Le lien qui dirige directement vers le page concernée : 
[https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=613%253A54250](https://us06st1.zoom.us/web_client/0urcsz4/html/externalLinkPage.html?ref=https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=613%25253A54250)

Vu ok [note: vu avec Ugo & Kale].

**Comment by lucaa** [comment]
Je rouvre le ticket pour traiter le problème suivant, glissé dans l'implémentation: 
* La section "Les 250 démarches suivies par l’Observatoire" ( la version "simplifiée" de la section "Comment évaluons nous la qualité des démarches") est également affichée pour les utilisateurs non-connectés, entre la section "Vous êtes porteur... " et "Questions":

![image](https://user-images.githubusercontent.com/657716/163453592-6f029a93-2448-4cb8-bd5e-1c11e327d542.png)

**Comment by ClemDee** [comment]
> Je rouvre le ticket pour traiter le problème suivant, glissé dans l'implémentation:
> 
>     * La section "Les 250 démarches suivies par l’Observatoire" ( la version "simplifiée" de la section "Comment évaluons nous la qualité des démarches") est également affichée pour les utilisateurs non-connectés, entre la section "Vous êtes porteur... " et "Questions":

Je n'avais pas vu que ce problème était décrit dans ce ticket, il a été résolu dans le commit 013306455a97a5d1d22610201b53e1502580172a de #1052, je ferme donc le ticket.
