### ISSUE TITLE
Ajout du bouton pour récupérer le code du bouton JDMA à partir de la liste "mes démarches" de la page d'accueil

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1054]
Dans liste des démarches "mes démarches", décrite par #1053 , à côté de chaque démarche, un bouton pour obtenir le code du bouton - "Installer le bouton...":

![image](https://user-images.githubusercontent.com/657716/158213084-b5871e24-15fc-41d2-a8a1-db0b91a55a8d.png)

Ce bouton pointe vers l'onglet de la démarche avec le code du bouton avec le code du bouton déjà généré, sans qu'aucune autre opération soit nécessaire de la part de l'utilisateur.

Le bouton est censé être affiché de manière différenciée selon si le code a déjà été intégré ou pas, mais pour des raisons de la spécificité de ces informations d'intégration, cette différenciation est prévue par une tâche séparée, #1090.

**Comment by ClemDee** [comment]
Implémentation du bouton d'installation de l'outil pour donner son avis depuis la page d'accueil.

**Comment by AnthonyBrunelli** [comment]
Vu ok [note: vu avec Ugo & Kale]
