### ISSUE TITLE
Modifier les pages d'inscription et de connexion pour ajouter des liens de l'une vers l'autre

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1056]
![image](https://user-images.githubusercontent.com/657716/135507023-99166eca-e0f3-4270-b1d0-15543ec3c596.png)

Mockup complet sur figma https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=90%3A24913

À faire, de ces écrans:
* connexion:
  * layout sur une seule colonne
  * mise à jour du texte
  * lien vers l'inscription
* inscription:
  * mise à jour du texte
  * lien vers la connexion

À ne pas faire:
* implémentation spécifique du dsfr - les seuls styles dsfr nécessaires sur ces écrans sont ceux apportés par #1051 
* suppression du captcha du formulaire d'inscription - d'ailleurs, ce n'est pas clair pourquoi cet élément a été enlevé et s'il a été remplacé avec autre chose (voir #508 pour le captcha)
* fusion des liens "j'ai oublié mon ..." dans le formulaire de connexion

**Comment by ugodtn** [comment]
Discuté ensemble de nouveau, on est d'accord avec ce qui est écrit ici.

**Comment by AnthonyBrunelli** [comment]
@lucaa @ugodtn on est d'accord que sur ce ticket, @lucaa peut lancer les travaux, rien en attente de notre côté?

**Comment by AnthonyBrunelli** [comment]
Les dev peuvent être lancé, confirmé avec Ugo.

**Comment by lucaa** [comment]
À ne pas faire, aussi:
* modification de signalement des champs obligatoires - dans les dernières maquettes (pas les images de cette tâche) les champs obligatoires sont signalés avec une étoile, contrairement au formulaire courant. La modification de ce signalement n'est pas incluse dans cette tâche.

**Comment by AnthonyBrunelli** [comment]
Attention, le bon lien est [https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=102%253A32745](https://us06st1.zoom.us/web_client/0urcsz4/html/externalLinkPage.html?ref=https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=102%25253A32745)

**Comment by AnthonyBrunelli** [comment]
> 

Nous n'avons pas compris ton dernier commentaire @lucaa : le signalement des champs obligatoires est important, mais il n'y a pas d'autre tâche si? Pour nous, la modification est à faire [note: vu avec Ugo & Kale]

**Comment by lucaa** [comment]
bq. Attention, le bon lien est https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=102%253A32745

Pour moi au moins, ça redirige vers le même lien que celui du corps de la tâche.

bq. Nous n'avons pas compris ton dernier commentaire @lucaa : le signalement des champs obligatoires est important, mais il n'y a pas d'autre tâche si? Pour nous, la modification est à faire [note: vu avec Ugo & Kale]

Mon dernier commentaire parlait du _changement_ du signalement des champs obligatoires vers le style de la maquette (avec étoile) par rapport à l'implémentation courante avec le mot "obligatoire" affiché entre parenthèses:

![image](https://user-images.githubusercontent.com/657716/160997536-5e743606-283f-4ad6-a538-f7cf6571f273.png)

et proposait de ne pas faire ce changement et garder l'approche courante. Le raisonnement est basé sur le fait que le style du formulaire lui-même n'est pas prévu pour changer dans le cadre de cette tâche, donc ne touchons pas au style des champs obligatoires non plus.

Je suis d'accord qu'il est important de signaler les champs obligatoires (ce qui est couvert, à priori), et si le _style_ de ce signalement est aussi important, on peut l'inclure dans la tâche courante.

**Comment by AnthonyBrunelli** [comment]
@ugodtn ?

**Comment by ugodtn** [comment]
@AnthonyBrunelli je me dis que ce n'est pas si critique, et qu'on fera cette modification de style quand on modifiera le style du formulaire pour qu'il passe au DSFR. Aujourd'hui les champs obligatoires sont bien indiqués.

**Comment by AnthonyBrunelli** [comment]
Voilà Anca pour la réponse :)

**Comment by ClemDee** [comment]
Ce qui a été fait : 
* Mise à jour des textes
* Mise en place des liens vers les pages de login / register
* Modification du layout de la page de login en une seule colonne
* Ajustement de quelques marges verticales entre certains éléments

**Comment by ClemDee** [comment]
> au dessus de ça, le texte prend 8 colonnes sur 12 et le formulaire 5.

En vrai il n'est pas possible de donner 5 colonnes pour le formulaires, car ces colonnes se feront par rapport au container de 8 colonnes, et non pas à la largeur totale de la page.

`5 / 8 * 12 = 7.5`, du coup on peut choisir soit `col-sm-7` ou `col-sm-8` pour la largeur du formulaire, afin d'avoir une taille la plus proche des 5 colonnes de la maquette.

> Sur mobile (tailles XS et SM dsfr)

L'affichage est très resséré et cassé pour des tailles juste au dessus de `sm` (bootstrap) avec les marges du contenu : 
![image](https://user-images.githubusercontent.com/45625842/169256739-610047fe-a9f5-46bd-bfac-c225d153274d.png)
(exemple de largeur de 780px)

C'est dû au fait que les champs "Identifiant / mdp oublié" sont des floats qui wrappent pas bien quand l'espace se réduit, et réduisent l'espace disponible pour l'input.

Et même pour des tailles au dessus de `md` (bootstrap) on peut voir ce problème si la taille du formulaire est trop petite (avec un `col-md-7` par exemple): 

![image](https://user-images.githubusercontent.com/45625842/169258219-5a07e825-14bb-4561-9ad3-07982756d02e.png)
(exemple de largeur de 1105px)

Dans les conditions ou j'utilise le breakpoint `md` _et_ un `col-md-8` pour la taille du formulaire, tout s'affiche à peu près bien, du coup je vais partir sur ça en attendant (surtout que les messages "indentifiant / mdp oublié" vont probablement changer par la suite pour suivre la maquette, ça permettra de supprimer ce problème).

**Comment by ClemDee** [comment]
Mise à jour du layout pour qu'il prenne 8 colonnes, et du formulaire pour qu'il prennet l'équivalent des 5 colonnes définies dans la maquette.

**Comment by lucaa** [comment]
je ne vois pas un formulaire de connexion sur une seule colonne sur dev, @ClemDee . peux-tu vérifier s'il manque quelque-chose à cette implémentation?

**Comment by lucaa** [comment]
> je ne vois pas un formulaire de connexion sur une seule colonne sur dev, @ClemDee . peux-tu vérifier s'il manque quelque-chose à cette implémentation?

trouvé: c'était lié à d'autres travaux en cours sur dev, le travail est bien fini, il n'y a pas de manque, je re-ferme.
