### ISSUE TITLE
Mise à jour du dsfr à la version de l'automne 2021 (> 1.1.0)

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1061]
Dès qu'une version nouvelle du DSFR est disponible, plus élevée que la 1.1.0 intégrée aujourd'hui pour #1015 , il faudra intégrer cette version.

**Comment by AnthonyBrunelli** [comment]
@lucaa @ugodtn on est d'accord que sur ce ticket, @lucaa peut lancer les travaux, rien en attente de notre côté?

**Comment by AnthonyBrunelli** [comment]
Confirmé par Ugo, rien de notre côté.

**Comment by ClemDee** [comment]
Mise à jour vers le dsfr v1.3.1 effectuée !
- La structure du dossier `dist/` ayant totalement changée, j'ai dû adapter mon script dsfr-scoper afin qu'il puisse regénérer les styles custom (je l'ai aussi rendu plus résilient face à de nouvelles MAJs)
- Le dsfr supporte maintenant IE11 ! :smiley: J'ai donc rajouté les styles `legacy` nécessaires quand il le fallait

**Comment by ClemDee** [comment]
Les fichiers du dsfr-scoped qui avaient été commits ne correspondaient pas à la dernière version du dsfr-scoper committé en même temps, ce qui posait problème pour les installations car le css compilé n'était plus bon. C'est fixé
