### ISSUE TITLE
Enlever le besoin d'avoir le paramètre nd_mode dans l'URL des formulaires d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1063]
Pour des raisons historiques, les avis contiennent une méta-donnée pour décrire comment la démarche a été réalisé: en papier au guichet, en ligne complètement ou en ligne partiellement (pour les démarches en ligne qui finissent en échec). 

L'usage courant de l'observatoire est construit uniquement autour des avis pour le chemin "en ligne complètement" - les boutons "à la fin de la démarche" (c'est discutable si c'est vraiment la réalité des intégrations mais en tout cas, c'est la logique de l'observatoire aujourd'hui).
Ainsi, le code d'intégration du bouton "Je donne mon avis" fourni aujourd'hui accès à un formulaire d'avis avec l'option "comment la démarche a été réalisé" pré-remplie avec la valeur "en ligne complètement". 

Aujourd'hui ce pre-remplissage est obtenu par le fait qu'il y a un paramètre dans l'URL du bouton avec la bonne valeur (le paramètre nd_mode).
Comme cette valeur contient un caractère avec accent, cela pose beaucoup trop de problèmes d'encodage lors de l'intégration du bouton, malgré le fait que l'onglet "code à intégrer" fourni une URL correctement encodée. Comme il n'y a pas vraiment d'usage pour les autres valeurs de ce paramètre, le plus simple pour résoudre ces problèmes d'encodage est de ne plus inclure ce paramètre _du tout_ dans l'URL du formulaire d'avis et de stocker la valeur "en ligne complètement" par défaut pour tous les avis. 

----

Le résultat fonctionnel de cette tâche est le suivant:
* dans l'onglet "code à intégrer", l'URL du bouton ne contient plus de valeur encodée (est uniquement ASCII)
* les URLs ainsi générées marchent et enregistrent des avis marqués comme réalisés en ligne complètement - comme c'était le cas avant
* les URLs précédemment générés marchent encore et enregistrent des avis marqués comme réalisés en ligne complètement aussi - les avis produites par les URLs avant et après sont identiques en terme de méta-données stockées (a part, bien sur, les réponses aux questions posées à l'utilisateur)

**Comment by lucaa** [comment]
Ce problème a déjà été remonté, sous une autre forme, dans #1005 . 
Comme ce ticket est plus complet, à la fois au niveau des explications qu'au niveau du résultat attendu, je vais marquer l'autre comme un doublon de celui ci.

**Comment by AnthonyBrunelli** [comment]
[note pour moi, explication d'Anca : Simplification de l'URL JDMA pour enlever une valeur problématique.]

**Comment by lucaa** [comment]
Le code est fait, mais pas encore déployé en production. La stratégie choisie est la suivante - voir aussi #1114:
* la méta-donnée modalité de l'avis est préservée dans la structure des avis (cette méta-donnée est remplie par les valeurs du paramètre nd_mode)
* si le paramètre nd_mode est présent dans l'URL du formulaire d'avis, la valeur de l'URL est utilisée pour la méta-donnée
  * si la valeur du paramètre n'est pas parmi les 3 valeurs possibles, l'avis n'est pas du tout stocké (ce comportement existe déjà, il n'est pas nouveau pour cette tâche)
* sinon, la valeur du champs modalité est remplie par défaut avec en-ligne-entièrement
* dans aucun cas on ne pose la question à l'utilisateur.

**Comment by lucaa** [comment]
> dans aucun cas on ne pose la question à l'utilisateur

ce choix mitige les bugs #772 et #1044 : désormais, lors du rafraîchissement de la deuxième étape du formulaire la première question du formulaire est re-posée à l'utilisateur mais les questions supplémentaires du formulaire ne sont plus jamais re-posées.
La "source" (référer, nd_source) du formulaire d'avis initial est, par contre, perdue lors de ce rafraîchissement - voir #772.
