### ISSUE TITLE
Obs - Bug sur le graph Cesu Déclarer les heures

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1068]
On a reçu un message qui dit:

"Ce msg pour vous signaler qu’en cliquant sur le bouton « Graphes » à la rubrique "CESU - Déclarer les heures » depuis https://observatoire.numerique.gouv.fr/observatoire/ on obtient le message "Failed to execute the [velocity] macro. Cause: [Timeout waiting for idle object]. Click on this message for details."

J'ai regardé, je confirme...

**Comment by AnthonyBrunelli** [comment]
![image](https://user-images.githubusercontent.com/35567048/148995655-0ab06620-b92e-4acd-ab1b-c4f4a07c6a19.png)

**Comment by lucaa** [comment]
Je ne vois plus l'erreur aujourd'hui, j'ai regardé l'écran https://observatoire.numerique.gouv.fr/Demarches/1662#statistics-tab en mode connecté.

Je n'ai pas les détails du problème pour essayer de comprendre exactement les détails de l'erreur, mais elle semble lié à un temps de calcul trop long pour les graphiques, et c'est une erreur qui peut être temporaire, liée à la charge du serveur et les temps de calcul du moment.
Par contre, il y a un cache mis en place pour tout cet écran, qui fait que même s'il y a une erreur temporaire, elle est mise en cache et aucun essai de récupérer la donnée n'est fait jusqu'à l'expiration de ce cache. Ces caches ont une durée de vie de 24h.

Des erreurs temporaires de ce type pourraient apparaître et ne seraient pas bloquantes, de mon point de vue, ce qu'il faudrait éviter est que lors d'un rafraîchissement de page ou nouvel accès, la même erreur soit présentée, sans même essayer de re-recuperer les données. Ceci rend une erreur temporaire permanente, ce qui n'est pas OK. 

L'amélioration de la gestion de la récupération des données pour ces écrans fait partie des travaux sur la performance de l'accès aux données, avec stockage de données agrégées, que nous avons discuté lors des nos discussions génériques d'architecture.  (qui devrait alléger considérablement les calculs à faire pour l'écran des graphiques d'une démarche). 

La tâche #866 serait un premier petit pas dans la direction d’alléger la charge du serveur au moment du calcul des caches des données "en direct".

**Comment by AnthonyBrunelli** [comment]
Je ferme en considérant que c'est éphémère et normalement résolu en parti par 866 + amélioration en cours avec les agrégats.
