### ISSUE TITLE
JDMA - L'utilisateur connecté qui ajoute une nouvelle démarche par le formulaire simplifié doit être automatiquement porteur de cette démarche

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1075]
Aujourd'hui un utilisateur "simple" peut ajouter une démarche uniquement par le formulaire simple (accessible suite à une recherche).

Lors de l'ajout de la démarche par cette méthode, l'utilisateur doit être automatiquement ajouté comme un porteur de cette démarche. Aujourd'hui l'utilisateur doit se déclarer comme porteur par une action supplémentaire après l'ajout de la démarche.

Ce changement de comportement fait partie de #1055 , et sera à faire quelque soit le parcours ou formulaire choisi pour l'ajout de la nouvelle démarche.

**Comment by lucaa** [comment]
En regardant les tickets existants pour le parcours porteur, je pense que c'est déjà le cas. 
À vérifier (peut-être que c'est codé comme ça mais ça ne fonctionne plus) et a implémenter si c'est pas le cas.

**Comment by lucaa** [comment]
> En regardant les tickets existants pour le parcours porteur, je pense que c'est déjà le cas.

Je confirme que c'est déjà le cas, l'utilisateur courant est ajouté comme porteur de la démarche ajoutée.
