### ISSUE TITLE
Obs - ne pas afficher le % RGAA si celui-ci n'est pas renseigné.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1078]
Cas discuté à l'oral. Dans l'Observatoire, les info complémentaires qui s'affichent en dessous de chaque ligne: ne pas afficher le %RGAA si l'info est vide.

**Comment by AnthonyBrunelli** [comment]
![image](https://user-images.githubusercontent.com/35567048/154284254-4dcc767f-fc32-4d3f-9ee0-455a7dc35b0d.png)

**Comment by lucaa** [comment]
Corrigé, pour tous les observatoires pour lesquels l'information est présente et le problème est visible.
