### ISSUE TITLE
Formulaire JDMA - Coquille en page 3

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1079]
Message d'origine:
"Bonjour, je me permets de vous informer qu'une erreur de frappe s'est glissée dans un de vos messages automatiques : "d'avantage" au lieu de "davantage". Cordialement,"

**Comment by AnthonyBrunelli** [comment]
![Davantage](https://user-images.githubusercontent.com/35567048/154983438-0b3793bd-e54d-453f-a14d-5c95537cd1a3.png)

**Comment by AnthonyBrunelli** [comment]
Patchable?

**Comment by lucaa** [comment]
C'est fait et installé en production.

**Comment by AnthonyBrunelli** [comment]
Vu et confirmé! Merci Anca!
