### ISSUE TITLE
Formulaire JDMA - Intitulés case à cocher à corriger

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1081]
Il faudrait modifier les cases à cocher de la manière suivante pour la partie "De quelle aide avez-vous eu besoin" :

De quelle aide avez-vous eu besoin ?
 -         Aucune
 -         Un(e) proche (famille, amis…)
 -         Un agent public (santé, enseignement, impôts, force de l’ordre, France services...)
 -         Une association 
 -         Internet (site, forum…)
 -         Autre

**Comment by AnthonyBrunelli** [comment]
@ugodtn Je te laisse jeter un dernier coup d'oeil pour être sûr que c'est bon, et passer ça en "to do blocker". Je pense qu'il faut un patch et ne pas attendre la 4.10.

**Comment by ugodtn** [comment]
@AnthonyBrunelli @lucaa Oui j'ai une remarque, je vois que la liste pour agent public est longue et vient gêner la lisibilité. Je propose d'apporter les précisions non pas entre parenthèses, mais en texte de description sous chaque champ, comme décrit [dans la doc du DSFR](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217251933/Case+cocher+-+Checkbox#Liste-avec-texte-d%E2%80%99aide). J'en profite pour laisser l'intitulé _Un ou une proche_.

Ça donnerait cela :
<img width="511" alt="Capture d’écran 2022-02-28 à 12 36 41" src="https://user-images.githubusercontent.com/34340568/155977039-8dbce4c9-8520-4a4b-9199-ac669c0088c8.png">

**Comment by ugodtn** [comment]
@lucaa j'ai validé ce point avec Marine, on peut lancer le développement si tout est ok pour toi !

**Comment by lucaa** [comment]
@ugodtn : ok, merci. Ça devient un peu plus complexe que juste le changement de l'intitulé car il faut ajouter les textes de description dont il n'y aucun aujourd'hui, mais pas énormément plus complexe.

@ugodtn voudrais tu profiter pour revoir l'autre question à cases à cocher pour utiliser la même technique? (la question sur les difficultés)

**Comment by lucaa** [comment]
vu au téléphone, pas d'autres modifications pour les autres cases à cocher.

**Comment by ClemDee** [comment]
Implémentation du système de hint pour les checkbox / radio buttons, et implémentation des nouvelles traductions associées

**Comment by lucaa** [comment]
C'est déployé en staging & production.

**Comment by AnthonyBrunelli** [comment]
'lut! Vu en prod, ça me semble ok (en tout cas ça correspond à la demande d'Ugo). @ugodtn tu veux regarder en prod avant que je ferme?
