### ISSUE TITLE
Mise en place des couleurs dsfr pour les écrans avec des couleurs spécifiques

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1084]
Il y a quelques écrans dans l'observatoire avec des couches de style propres qui personnalisent les styles hérités du thème de couleurs.

Il faudrait s'assurer que ces écrans utilisent les couleurs du dsfr / du thème de couleurs dsfr.

Notamment, traitons au moins les éléments suivants, surtout qu'une partie des couleurs ont été perdues lors des changements pour #1051 :
* ~~l'observatoire - **par contre ne pas toucher _aux couleurs des indicateurs_ dans le tableau,** le contraste de ces couleurs est très sensible et les informations diverses, il faudrait un chantier plus avancé pour les changer:~~
  * ~~bandeaux colorés en haut~~
  * ~~bouton "back to top" affiché lors du scroll~~
* ~~la page d'accueil - uniquement les couleurs 'basiques'. Une tâche est dédié pour une refonte plus poussée dans #1052 .~~
* ~~la page des graphiques d'une démarche, où un bleu a été remplacé par un gris suite à #1051 (pour Historique des avis > Indice de satisfaction global). Les autres changements de nuances, suite aux changements du thème de couleurs peuvent rester ceux du dsfr.~~

Plus globalement, s'il y a des variables de couleur définies dans le thème de couleurs avant #1051 qui ont été effacées / ne sont plus disponibles partout / ont changé de nuance, il faudra auditer tous les usages de ces variables et corriger (ou s'assurer qu'il y a des tickets pour leur correction dans milestone 4.10).

**Comment by lucaa** [comment]
J'ai créé des tâches spécifiques pour la page de l'observatoire ( #1084 ) et des graphiques d'une démarche ( #1085 ) donc il reste à faire dans cette tâche uniquement la recherche des autres usages des couleurs qui ne font pas partie du thème de couleurs, pour corriger / identifier les autres endroits.

**Comment by ClemDee** [comment]
Il y a encore 2 couleurs qui ne respectent pas le thème dsfr : 
- la couleur du focus : celle-ci est [hard codée](https://github.com/GouvernementFR/dsfr/blob/a734e4093658f1eae8bc1757652cb967604ad219/src/core/style/color/setting/_static.scss#L6) à `#0a76f6` 
- la couleur du fond bleu dans le formulaire d'avis : celle-ci vaut `#f2f2f9` et correspond à la couleur `fr-bf100` de l'ancienne implémentation du dsfr version `1.1.0`, qui ne respectait pas le thème de couleur de la spécification

**Comment by kamalcon** [comment]
- Normalement #0a76f6 est dans le DSFR : $focus-525
- la couleur fond bleu pourrait être remplacé par $blue-france-975

**Comment by ClemDee** [comment]
> Normalement #0a76f6 est dans le DSFR : $focus-525

Étrange, il m'est impossible de trouver cette couleur ni dans les [spécifications](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217186370/Couleurs+-+palette+-+Color), ni dans [l'implémentation](https://github.com/GouvernementFR/dsfr/search?q=focus-525).

> la couleur fond bleu pourrait être remplacé par $blue-france-975

Ok je met à jour

**Comment by ClemDee** [comment]
Les anciennes variables du style ont été mises à jour et utilisent désormais des couleurs de la spécification DSFR.

Je ferme ce ticket, d'éventuelles modifications à apporter par rapport à la couleur du focus pourront être traitées dans un nouveau ticket.
