### ISSUE TITLE
Mise en place des couleurs DSFR pour la page de l'observatoire

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1086]
Le besoin générique de couleurs suite à la mise en place de #1051 est décrit dans #1084 , cette tâche est pour préciser (et éteindre) le besoin pour la page de l'observatoire.

La page courante, en dev, après implémentation de #1051 :
![image](https://user-images.githubusercontent.com/657716/156758657-f3fae4bb-9bd2-4d24-a9d8-8ca69d001a45.png)

La page en production, avant implémentation de #1051: 
![image](https://user-images.githubusercontent.com/657716/156758610-8857bbd4-2301-4ff1-b4a3-c7848723bca7.png)

Couleurs qui ne font pas partie du thème de couleurs et qui doivent être décidés et mis en place au niveau de ce ticket:
* bandeau(x) bleus avec le titre de la page et les boutons de partage et lien vers l'open data - couleur de fond et de texte
![image](https://user-images.githubusercontent.com/657716/156759950-6d5146ea-5e2a-44d8-aacc-af5c275771a6.png)
* pictogrammes pour la tête de tableau - sachant que ces mêmes pictogrammes sont actuellement sur la page d'accueil aussi et que leurs couleurs devraient (pourraient) être identiques que celles de la PA (redesign prévu dans #1052 mais aucune spécification de couleurs)
![image](https://user-images.githubusercontent.com/657716/156759121-987de729-722e-4a6d-a0c5-9c3693415d3c.png)
* couleurs des indicateurs dans le tableau - couleur de fond et de texte, sachant qu'il y a les couleurs suivantes:
** gris (neutre), vert (OK), rouge (NOK), orange (avertissement) pour toutes les colonnes. 
** une couleur bleu supplémentaire (neutre?) pour la première colonne - statut de la démat  pour les valeurs "Bêta"
** pour la colonne Usagers satisfaits la couleur de fond est utilisée uniquement pour un contour, pas comme un fond complet (je ne me rappelle plus pourquoi on a un affichage spécial pour cette colonne, il faut que je cherche dans les tickets - je pense que c'était une histoire d'éviter un classement trop prononcé des démarches par les avis utilisateurs).
![image](https://user-images.githubusercontent.com/657716/156759904-9fef10e3-5ae1-42bb-8b49-71b621ca55ce.png)

Cette tâche comprend la spécification des couleurs et leur implémentation.

**Comment by AnthonyBrunelli** [comment]
Ce point me semble traité. Je ferme.

**Comment by lucaa** [comment]
> Ce point me semble traité. Je ferme.

Non non, ce n'est pas fait. 
* il reste une couleur à définir côté Dinum (le bleu mentionné ci-dessus)
* il reste l'implémentation à faire.

**Comment by AnthonyBrunelli** [comment]
Pardon ! @ugodtn tu as la réponse pour la couleur bleue?

**Comment by kamalcon** [comment]
Tag bleu ajouté https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=775%3A54554 @lucaa

**Comment by ClemDee** [comment]
Ce qui a été fait : 
- Mise à jour des couleurs du bandeau bleu
- Mise à jour de la couleur des indicateurs
- Mise à jour de la couleur du fond des icones

Ce qui n'a pas été fait : 
- La couleur des icones n'a pas été touchée, car celles-ci seront modifiées pour la page d'accueil (et donc le problème de couleur sera résolu ici)
- certaines couleurs liées au comportement de boutons lors du survols / interactions, ainsi que d'autres couleurs non spécifiées dans la maquette n'ont pas été touchées.

**Comment by ClemDee** [comment]
Il reste encore quelques couleurs non-dsfr `@obs-blue` qui n'ont pas été remplacées, car elle sont utilisées lors du survols / clic sur certains boutons, dont les specs ne sont pas spécialement énoncées. Les boutons en question sont les boutons de filtre et de tri des démarches, ainsi que les boutons des tabs "Tableau" et "Détails" de la page.

Du coup doit-on garder les styles dsfr par défaut pour ces types de comportements, où y a-t-il des styles customs à mettre en place pour ces boutons ?

@lucaa À ce sujet, les styles dsfr des comportements des boutons au survol / click implémentés dans le DSFRTheme ne correspond pas à celle de l'implémentation actuelle du dsfr. Les styles dans la Theme liés à ces comportements sont ceux de bootstrap, et du coup les couleurs au survol / clic ne sont pas correctes. Du coup si on veut garder le comportement du dsfr par défaut pour les boutons de la page des démarches, il va falloir mettre à jour les styles des boutons dans la DSFRTheme.

**Comment by lucaa** [comment]
En ce qui concerne les usages de @obs-blue:
idéalement, on devrait s'en débarrasser complètement, il n'y a pas de raison de traîner encore cette couleur. Ainsi, ce que je te propose, @ClemDee , est de remplacer la couleur, dans ces usages, avec la couleur avec laquelle obs-blue a été remplacée aux autres endroits auxquels elle était utilisée (je pense que ça fait blue-france-sun-113  - la couleur du bandeau).

> Du coup doit-on garder les styles dsfr par défaut pour ces types de comportements, où y a-t-il des styles customs à mettre en place pour ces boutons ?

Pour l'instant ne mettons pas à jour les styles des boutons au survol / click. On peut faire ça dans une tâche séparée, occupons-nous uniquement des couleurs dans le cadre de la tâche courante.

**Comment by ClemDee** [comment]
La couleur osb-blue a été supprimée de la page de l'observatoire

**Comment by ugodtn** [comment]
@kamalcon ça me semble ok, c'est bon pour toi ?

**Comment by kamalcon** [comment]
Oui c'est bon à part de la question d'orange qu'on traite dans #1087
