### ISSUE TITLE
Choix des couleurs de success / info / avertissement / erreur pour le thème de couleurs DSFR

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1088]
Pour #1051 , des couleurs ont été choisies à base de DSFR 1.1.0 et les couleurs ont changé pour la nouvelle version.

Cette tâche est pour clarifier les couleurs à utiliser pour les 4 éléments suivants, à partir de la palette https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217186370/Couleurs+-+palette+-+Color :

![image](https://user-images.githubusercontent.com/657716/157431649-033736ed-22ac-4f77-bf18-fdd3d342e8cd.png)

Ces couleurs sont utilisées pour colorer les graphes des avis d'une démarche, dans #1087 .

**Comment by ClemDee** [comment]
Done in #1084 ([b72246d](https://github.com/DISIC/observatoire/commit/b72246dd39fe2003aefb6b2b302f9357a3e1a2e0#diff-6fd7c41aa96fa638ad03dc2e29f0fb7c3481a75b1fe3ec1583c4e185125e0f97R1456))

**Comment by lucaa** [comment]
Re-ouvert parce-que l'objectif est d'avoir ces couleurs choisies validées par la Dinum.
@ugodtn: Les couleurs choisies sont:
* @brand-primary: @blue-france-sun-113;
* @brand-success: @success-425;
* @brand-info: @info-425;
* @brand-warning: @warning-425;
* @brand-danger: @error-425;

**Comment by lucaa** [comment]
Voir ce commentaire pour des informations sur les couleurs: https://github.com/DISIC/observatoire/issues/1087#issuecomment-1070980925 .

**Comment by ClemDee** [comment]
Les informations des couleurs sur figma correspondent bien aux couleurs que nous avions choisies.
Il n'y a donc plus rien à faire, je ferme le ticket.
