### ISSUE TITLE
Suppression du bouton "ajouter une nouvelle démarche" de la liste de résultats de la recherche rapide 

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1091]
Aujourd'hui lors de la recherche d'une démarche à partir de la page d'accueil, dans la liste de résultats de la recherche rapide, le bouton d'ajout d'une nouvelle démarche est affiché à la fin:

![image](https://user-images.githubusercontent.com/657716/158219645-f109e92c-09c0-4b3a-bb4d-c1defdb5d50f.png)

Le message + bouton doivent être supprimés de la liste de résultats rapides (mais laissés sur la page de résultats détaillés de la recherche).

**Comment by AnthonyBrunelli** [comment]
Vu ok [note: vu avec Ugo & Kale].

**Comment by lucaa** [comment]
@ClemDee il me semble que t'as fait cette modification dans le commit 51c81ac7b8db677ea8e06afa17242a22520656bc pour #1053 ,  mais je ne trouve pas de trace de lien de #1053 à cette tâche, donc c'est pas clair pour moi si t'as bien visé le comportement décrit ici ou autre chose...

Tu confirmes que c'est bien le fonctionnement décrit dans la tâche courante que t'as implémenté? Est-ce qu'il reste quelque chose à changer du point de vue fonctionnel?

**Comment by ClemDee** [comment]
@lucaa En effet je confirme, j'ai retiré ce bouton dans #1053 mais je n'ai pas référencé ce ticket, tout simplement car je ne savais pas qu'il existait :)

À propos de la phrase :
> Le message + bouton doivent être supprimés de la liste de résultats rapides (mais laissés sur la page de résultats détaillés de la recherche).

J'ai supprimé le bouton de la barre de recherche (quelque soit l'endroit), mais du coté de la page de résultats détaillés, il y a en bas un texte et un bouton similaire :

![image](https://user-images.githubusercontent.com/45625842/167587386-1e474037-75d0-4700-820c-6d2081fa3aa9.png)

Est-ce ce texte / bouton que tu décris pour la page de résultats détailles, ou est-ce qu'il faut en plus garder l'ancien texte / bouton d'ajout rapide directement depuis la barre de recherche ?

**Comment by lucaa** [comment]
> J'ai supprimé le bouton de la barre de recherche (quelque soit l'endroit), mais du coté de la page de résultats détaillés, il y a en bas un texte et un bouton similaire :
> Est-ce ce texte / bouton que tu décris pour la page de résultats détailles, ou est-ce qu'il faut en plus garder l'ancien texte / bouton d'ajout rapide directement depuis la barre de recherche ?

C'est ce bouton là dont le parle quand je parle de résultats détaillés. L'implèm courante me parait correcte, si en plus elle est intentionnelle et pas uniquement un effet de bord, c'est bon pour cette tâche.

Je vais laisser le ticket ouvert car je voudrais assurer que _tout_ le code ajouté pour cette fonctionnalité est correctement nettoyé de la code base.

**Comment by lucaa** [comment]
Il restait un bout de CSS spécifique à ce bouton, je l'ai supprimé. Je ferme le ticket maintenant.
