### ISSUE TITLE
Afficher "pas de résultats" dans la recherche rapide s'il n'y a pas de résultats

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1092]
Aujourd'hui lorsqu'une recherche rapide n'a pas de résultats, le bouton pour ajouter une nouvelle démarche est affiché, mais pas de message qu'il n'y a pas de résultats:

![image](https://user-images.githubusercontent.com/657716/158220252-23e331e9-ce47-488a-a95b-e97e56f25180.png)

Le bouton d'ajout de nouvelle démarche doit être enlevé (comme décrit par #1091) et, pour le cas ou il n'y a pas de résultats, un message doit être affiché.

**Comment by AnthonyBrunelli** [comment]
Mise à jour en prenant en compte le point soulevé ci-dessous (lucaa 14 mars) : pour ne pas induire l'utilisateur en erreur et pour être sûr qu'il accède à l'intégralité de l'information, **ne pas mettre de message lorsqu'il n'y a pas de résultat rapide**. Ainsi l'utilisateur cliquera sur "entrée" et sera redirigé vers la page de résultat détaillée. 
[note: vu avec Ugo & Kale]
