### ISSUE TITLE
Refonte de l'onglet pour récupérer le code du bouton JDMA

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1094]
L'objectif est d'obtenir le résultat suivant:

![onglet bouton JDMA](https://user-images.githubusercontent.com/657716/158224417-80c9250e-d8b9-496e-a834-ad987c7db37f.jpg)

Mockup complet sur figma ici: https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=90%3A24913 .

à faire:
* changement du nom de l'onglet;
* changement des textes et ajout des nouveaux textes explicatifs;
* les questions réponses de la section accordéon en bas ("ou placer le bouton" et "comment présenter le bouton...") doivent être idéalement isolés dans une page de contenu pour qu'elles puissent être facilement mises à jour par l'administrateur dinum.

à ne pas faire:
* le look & feel DSFR de la page, les seules décorations DSFR sont celles incluses dans #1051 .
* modification des outils de bas de page de la démarche - Commentaires, Pièces jointes, Historique, Pages liées.

**Comment by AnthonyBrunelli** [comment]
Vu ok [note: vu avec Ugo & Kale]

**Comment by lucaa** [comment]
Le nouveau look & feel de l'onglet a été mis en place, à l'exception de quelques détails, qui ne sont pas planifiés pour implémentation pour l'instant (des nouvelles tâches sont à créer s'il faut les implémenter):
* utilisation des headings de niveau 4 pour les titres "bouton blanc" et "bouton bleu"; je me demande si c'est correct du point de vue de la hierarchie de titres RGAA  - voir question sur Figma;
* dans la maquette Figma, des nouveaux retours à la ligne ont été ajoutés dans le code à copier, ils n'ont pas été implémentés car je n'ai pas vraiment compris leur utilité et j'ai préféré garder le code simple
* les dimensions des boites qui présentent le code à copier: aujourd'hui l'implémentation est basée sur des elements textarea en mode lecture seule et cela semble être le cas pour la maquette aussi. J'ai gardé la même implémentation. Par contre, il est difficile de dimensionner une textarea pour s'éteindre pour accueillir son contenu, elle a une taille fixe, donnée en nombre de lignes visibles. J'ai modifié cette taille à 7 lignes (de 5) pour que le contenu courant s'affiche entier pour une taille de police de 16px et pour la taille de l'écran lg.
* quelques modifications de tailles sur mobile n'ont pas été faits:
  * le changement de taille des titres "bouton blanc" et "bouton bleu"
  * le changement de l'espacement entre les blocks de 32 à 48
  * la modification de la taille de la boite avec le code à copier sur mobile - elle semble passer à 2 lignes sur Figma.

La vue mobile sur une colonne a été implémentée pour les tailles DSFR xs et sm (taille sm bootstrap).

**Comment by lucaa** [comment]
Les questions de FAQ ne se ferment pas quand une autre s'ouvre. J'ai reouvert pour investiguer.

**Comment by lucaa** [comment]
Corrigé, il manquait un bout de markup.
