### ISSUE TITLE
Génération automatique du code du bouton JDMA lors de l'accès à l'onglet

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1095]
Aujourd'hui (v 4.9), l'accès au code du bouton JDMA  pour le porteur est faite en 2 étapes:
* se rendre sur l'onglet "Code à intégrer"
* clicker sur le bouton "Générer le code"

L'objectif de cette tâche est de ne plus devoir cliquer sur le bouton "Générer le code" et de générer le code automatiquement à l'activation de l'onglet, pour rendre fluide le parcours du nouveau porteur de démarche.

**Comment by AnthonyBrunelli** [comment]
Ce qui est décrit juste ci-dessus (lucaa 14 mars 18h49) convient ! [note: vu avec Ugo & Kale]

**Comment by lucaa** [comment]
> s'assurer que lors du click sur le bouton "Installer le bouton... " de la page d'accueil connectée - https://github.com/DISIC/observatoire/issues/1054 - le code est généré et l'utilisateur est positionné sur l'onglet du bouton JDMA;

Ceci a été fait dans commit 58cddb756e553b6ed4eb78c2d3bb8c811540d33e pour #1054 par @ClemDee .

Il reste la deuxième génération du code à faire.

**Comment by lucaa** [comment]
Pour la génération du code pour le porteur lors de l'ajout d'une démarche j'ai utilisée la même technique que celle utilisée pour la page d'accueil ce qui fait en total 2 redirections dans ce cas:
* le formulaire d'ajout redirige vers la page qui génère le code pour l'utilisateur courant
* qui redirige ensuite vers la page de la démarche.

Ainsi, lorsque l'utilisateur se retrouve sur la page de la démarche après ajout, son code est déjà généré.
