### ISSUE TITLE
Implémentation du visuel DSFR pour le message annonçant que la démarche n'a pas d'avis sur l'onglet "graphes"

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1096]
Résultat attendu:

![onglet Synthèse des avis](https://user-images.githubusercontent.com/657716/158233289-21d2d9be-e591-40ed-8ff4-20a770bfb2ef.jpg)

La capture est pour l'utlisateur connecté mais l'affichage doit être similaire pour l'utilisateur non-connecté, lors d'un accès par URL direct (ou observatoire?).

Mockup complet sur Figma ici: https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=328%3A47272 .

à faire: 
* mise à jour du texte du message de la démarche sans avis
* affichage du message "cette démarche n'a pas encore d'avis"  avec le style DSFR

à ne pas faire:
* style DSFR des onglets
* modification des outils de bas de page de la démarche - Commentaires, Pièces jointes, Historique, Pages liées.

**Comment by AnthonyBrunelli** [comment]
Vu ok [note: vu avec Ugo & Kale].

**Comment by lucaa** [comment]
C'est fait, l'affichage est désormais DSFR. Un style générique a été ajouté dans le thème DSFR pour pouvoir faire des boites d'alerte avec des titres, comme dans DSFR (voir https://github.com/DISIC/observatoire/issues/1119#issuecomment-1147712219 ).
