### ISSUE TITLE
Bug d'accès aux démarches

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1098]
Je trace ici quelques exemples de problèmes/bugs d'accès aux données des démarches :

**Comment by AnthonyBrunelli** [comment]
Rapporté par Joffrey:
par rapport aux temps de chargement très longs par exemple, je n’arrive pas à accéder à cette démarche : https://observatoire.numerique.gouv.fr/Demarches/2219
Cela ne fonctionnait pas ce matin, puis fonctionnait parfaitement à midi, puis ne fonctionne plus. 
voilà ce sur quoi 
je tombe après 10 minutes d’attente : 
![image (3)](https://user-images.githubusercontent.com/35567048/158438662-7c8edc91-5386-4e46-b6f0-24e33bd41046.png)

**Comment by AnthonyBrunelli** [comment]
Autre exemple, sur la page admin des avi
<img width="1137" alt="Screenshot 2022-03-15 at 12 20 58" src="https://user-images.githubusercontent.com/35567048/158439764-460734ba-00e1-4a5a-b420-a6aa07fe9a2c.png">
s
https://observatoire.numerique.gouv.fr/Avis/Admin/Statistiques/

**Comment by AnthonyBrunelli** [comment]
Ce qu'on s'est dit (point Anthony Anca):
- pour le premier cas, il faut tracer URL date heure minute pour une bonne analyse du problème.
- pour le deuxième, la recherche sur tout les avis ne fonctionnent pas (trop d'avis). Il faut passer par SolR https://observatoire.numerique.gouv.fr/Avis/Admin/SolrSearch/
- pour les deux cas, il faut modifier le message valable aussi pour les utilisateurs du formulaire JDMA (message unique) en supprimant toute réf à VoxUsagers (je fais un autre ticket).

**Comment by jrenauxdinum** [comment]
Hello ! Nous avons essayé à de nombreuses reprises de charger cet url mais nous ne parvenons pas à charger la page. Nous en avons besoin afin de MAJ l'Observatoire (la démarche vient de rentrer dans le top 250 et avait déjà le bouton JDMA)
https://observatoire.numerique.gouv.fr/Demarches/2219?view-mode=statistics&date-debut=2021-04-01&date-fin=2022-03-31

**Comment by jrenauxdinum** [comment]
Nous avons besoin des statistiques de Satisfaction de la démarche 2219 du 01.04.21 au 31.03.22 pour la prochaine publication de l'Observatoire. Je viens de relancer la page mais cela ne fonctionne toujours pas :(

**Comment by AnthonyBrunelli** [comment]
@lucaa on a eu le problème aujourd'hui. Probablement dû a des manip de notre côté pour aller chercher des verbatims sur des grosses démarches (je dois voir ce qu'il a fait exactement avec Joffrey, et moi aussi j'ai dû lancer des trucs de mon côté). Tu peux confirmer? (ou pas...)

Par ailleurs, il faut qu'on change le message, absolument. Je vais voir si on a déjà un ticker sur le sujet sinon je l'ajoute.

**Comment by AnthonyBrunelli** [comment]
(vu c'est en staging pour le message #1103 )

**Comment by jrenauxdinum** [comment]
Pour ma part ce que j'avais fait c'était : essayer d'exporter 10K avis sur la démarche 823
L'url était le suivant : https://observatoire.numerique.gouv.fr/Demarches/823#liste-avis-tab%7Ct=avis&p=1&l=10000&s=autre&d=desc

Il n'avait pas abouti

**Comment by AnthonyBrunelli** [comment]
Problématique  suivie dans le cadre de la #1180 donc je ferme ici.

**Comment by AnthonyBrunelli** [comment]
N'embarque pas les problèmes sur les avis détaillés, car pas couvert sur les agrégats. Prévu ultérieurement avec l'archivage.
