### ISSUE TITLE
Modification du message d'erreur pour indisponibilité

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1103]
Le message est unique, il doit être valable pour tous les profils utilisateurs de l'Obs, dans tous les cas ET pour les utilisateurs du formulaire JDMA.

**Comment by AnthonyBrunelli** [comment]
![Message indisponibilité](https://user-images.githubusercontent.com/35567048/158998474-5e9abe75-412a-4f01-aed9-197aa9380939.png)


Ceci est le message à modifier

**Comment by AnthonyBrunelli** [comment]
Nouveau message 

Madame, Monsieur,

Le service est temporairement indisponible, veuillez nous en excuser. Nous vous invitons à l'utiliser un peu plus tard si possible.

Cordialement,

L'équipe technique.

@ugodtn Joffrey, ok pour vous?

**Comment by AnthonyBrunelli** [comment]
Titre (gros gras) : Le service est temporairement indisponible
Texte : Veuillez nous excuser. Nous faisons de notre mieux pour régler ce problème dans les plus brefs délais.

Voilà @lucaa , c'est la version définitive, tu peux apporter le correctif :)

**Comment by lucaa** [comment]
Les textes ont été mis à jour pour obtenir le résultat suivant: 

![image](https://user-images.githubusercontent.com/657716/170664433-e9403f56-5414-4b77-b5a0-1ee69905a3d2.png)

J'ai également ajouté des règles pour assurer la police sans serifs pour cet écran, pour des raisons de coherence avec la plateforme.
