### ISSUE TITLE
Page démarche - Accordéon

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1105]
Mettre les informations sous forme d'accordéon avec le premier "info générales" déplié par défaut 
https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=611%253A56809

[note: vu avec Ugo & Kale]

**Comment by lucaa** [comment]
à inclure aussi : le style des contenus de l'accordéon déplié https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=611%3A56809 .

**Comment by lucaa** [comment]
Sans:
* icône profil utilisateur

**Comment by lucaa** [comment]
Aussi, sans le layout en 10 colonnes sur 12. On reste sur 12 colonnes, comme aujourd'hui.

**Comment by lucaa** [comment]
@ClemDee à faire:
* changement du layout de l'onglet "informations" de la page de la démarche pour utiliser une seule colonne
* implémentation d'un accordéon bootstrap pour les sections qui sont aujourd'hui des panels bootstrap
  * attention au mode édit
  * attention à la page d'ajout de nouvelle démarche qui utilise le même formulaire avec des champs en moins
    *  à choisir entre: ouvrir l’accordéon par défaut pour cette écran ou ne pas mettre du tout d'accordeon (plus long et plus complèxe)
    * l'objectif est de fermer cette tâche avec un résultat utilisable, S'il y aura besoin de travail supplémentaire pour la page d'ajout de nouvelle démarche, on peut faire une tâche supplémentaire.
* tentative de décorer cet accordéon comme un accordéon dsfr
