### ISSUE TITLE
Profil porteur de démarche - Accès à la page code

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1106]
Lorsqu'un porteur de démarche créer une démarche, la page "code" apparaît dans son arborescence : ce ne doit pas être le cas.

**Comment by AnthonyBrunelli** [comment]
![image](https://user-images.githubusercontent.com/35567048/160835819-2b243940-f169-483b-b594-40ffb99fb778.png)

![image](https://user-images.githubusercontent.com/35567048/160835938-52537cf4-55a0-421e-a770-9bb50eb3faa8.png)

**Comment by lucaa** [comment]
Première amélioration à faire: enlever le listing des pages cachées, il n'y a pas de raison. 
Ainsi, même si les porteurs accèdent à cette page, ils ne voient pas le listing de scripts.

**Comment by lucaa** [comment]
> Première amélioration à faire: enlever le listing des pages cachées, il n'y a pas de raison.

ticket séparé créé dans #1117

**Comment by lucaa** [comment]
L'amélioration pour ne pas afficher les pages cachées dans ce listing a été faite, dans #1117 et le fil d'Ariane sera caché pour #1035. 

Néanmoins, l'écran d'ajout de nouvelle démarche peut (et devrait) être déplacé pour ne pas être dans l'espace de 'code', mais le besoin pour cette tâche n'est plus urgent. Ainsi, je déplace cette tâche dans la version post 4.10.

L'accès à la page code y est toujours, si le porteur manipule l'URL manuellement.

**Comment by AnthonyBrunelli** [comment]
Ok donc cette tache est ok SAUF s'il vient l'idée à un porteur d'écrire l'URL a la mano c'est ça?

**Comment by lucaa** [comment]
> Ok donc cette tache est ok SAUF s'il vient l'idée à un porteur d'écrire l'URL a la mano c'est ça?

Oui.

sachant que c'est un accès en mode lecture uniquement et il n'y a rien de secret la-dedans, le code en mode lecture y est déjà en mode lecture sur internet, dans ce répo github :) .

**Comment by AnthonyBrunelli** [comment]
Ok donc je ferme.
