### ISSUE TITLE
Mise en place des tailles de polices de la page d'accueil conformes aux maquettes

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1111]
Suite à l'implémentation de #1052 la nouvelle page d'accueil est en place, par contre les tailles de polices ne semblent pas correspondre aux tailles de polices de figma:

https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=540%3A51476

La base de conversion 16px = 1em doit être utilisée pour traduire les tailles figma (en pixels) en tailles web en em, sensibles aux préférences utilisateur.

**Comment by ClemDee** [comment]
La taille de la police a été mise à jour pour que 1rem soit bien égal à 16px.

Les hauteurs des tuiles de la page d'accueils étant hard-codées, celles-ci ont aussi été mise à jour afin de s'adapter à la nouvelle taille de texte.
