### ISSUE TITLE
Mise en place des nouvelles icônes pour les indicateurs de la qualité de la dématérialisation

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1115]
Cf maquette figma:

![image](https://user-images.githubusercontent.com/657716/166212785-5246680a-3649-4837-8878-a24921707396.png)

De https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=540%3A51476 .

Les mêmes icoônes doivent être mis en place dans la tête du tableau de la page observatoire.

**Comment by lucaa** [comment]
@ugodtn peux-tu confirmer que cette tâche est à faire?

**Comment by AnthonyBrunelli** [comment]
Tu veux dire dans la 4.10 ?
Il me semble que dans tous les cas, c'est à faire. Les icônes posent un problème particulier?

**Comment by lucaa** [comment]
@AnthonyBrunelli oui, dans la 4.10, mais aussi dans le sens de "est-ce que la maquette est définitive, décision prise et validée, peut-on commencer le travail dessus?"
(pour l'historique & contexte: on avait discuté de la _possibilité_ de changer les icônes début mars, mais à ce moment @ugodtn m'a conseillé d'attendre que ça soit décidé avant de créer une tâche; vendredi j'ai observé que les maquettes ont été mises à jour, donc j'ai créé cette tâche et maintenant je confirme que l'implémentation est à planifier).

**Comment by AnthonyBrunelli** [comment]
Donc non, pas validé (j'ai un problème avec l’icône pour le handicap). Désolé, bug de notre côté. Je m'en occupe.

**Comment by AnthonyBrunelli** [comment]
@lucaa Merci pour le point, du coup on a revu 3 choses : 

1. Les pictos
2. L'intitulé "support accessible"
3. L'ordre de présentation.

Kale va joindre les maquettes mises à jour (merci Kale!).

Je vais faire des tickets pour les points 2 et 3, notamment parce que l'Observatoire doit être adapté en fonction (ordre et intitulé des colonnes).

Il faut que je voie aussi où apparaît "support accessible" pour le remplacer.

**Comment by kamalcon** [comment]
Maquette à jour : https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=540%3A51476 - note : la description pour chaque indicateur est toujours du placeholder texte, pas finalisé. Seulement les titres sont validés.

**Comment by kamalcon** [comment]
Note : nous avons harmoniser le titre du bouton `En savoir plus sur les indicateurs` avec le bouton sur l'accueil connecté. Nous avons aussi changé le texte de l'autre bouton : `Suivre la satisfaction de vos usagers`

**Comment by AnthonyBrunelli** [comment]
Il faudra changer du coup les pictos sur le tableau de l'Obs aussi...

**Comment by lucaa** [comment]
> Il faudra changer du coup les pictos sur le tableau de l'Obs aussi...

Oui, c'est prévu dans la tâche à la base, dans la description.

**Comment by ClemDee** [comment]
* remplacement des anciennes icônes par les nouvelles.
* très légère modifications des styles pour centrer les icônes à l'intérieur du cercle, ajustement de la tailler des icônes
* suppressions des anciennes icônes non utilisées
