### ISSUE TITLE
Implémentation des décorations DSFR pour toutes les boîtes de messages de la plateforme

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1119]
À plusieurs endroits de l'implémentation DSFR, des boîtes d'information / erreur / etc sont affichés.

Cette tâche est pour implémenter les décorations DSFR pour les _wells_ standard bootstrap, comme une surcouche qui s'applique à tous les éléments bootstrap avec leur markup standard.

L'objectif est d'obtenir le visuel DSFR sans toucher au markup, le plus possible (l'étude de la faisabilité fait aussi partie de cette tâche.

L'objectif est que toute boîte valide XWiki (ajoutée avec les macros dédiées info, success, warning et error) soit décorée.

**Comment by lucaa** [comment]
Quelques boîtes qui devraient être décorées lors de l'implémentation de cette tâche (liste non-exhaustive):
* le message de succès lors de l'ajout d'une démarche - #1093
* les messages du nombre d'avis pour #1096 et #1097
* le message permettant à un utilisateur connecté de se déclarer porteur d'une démarche .

**Comment by ClemDee** [comment]
Le style DSFR à été implémenté dans le DSFRTheme XWiki pour les alerts.

![image](https://user-images.githubusercontent.com/45625842/168775789-207790b7-611d-4b21-a33e-0bfb0b17336a.png)

**Comment by lucaa** [comment]
@ClemDee le cadre (border) des boîtes du message ci-dessus me paraît pas à la bonne couleur (au moins à base des mockups figma, il à l'air de devoir être à la couleur de l'icône. Je rouvre pour valider cela.

**Comment by ClemDee** [comment]
* Implémentation du style DSFR pour les alertes des macros XWiki
* Fix de la couleur des bordures des alertes

![image](https://user-images.githubusercontent.com/45625842/168843268-114d78ab-5ad7-4f2c-b95a-52b69b4f43c7.png)


Aperçu pour #1093 : 

![image](https://user-images.githubusercontent.com/45625842/168843117-f1fcb6a4-9a46-4874-a528-6b4cb5462d81.png)

**Comment by lucaa** [comment]
> Les alertes bootstrap ne prévoyant qu'une seule taille possible d'alerte, il n'est donc pas possible de différencier les deux variantes du dsfr, seule la taille normale est donc implémentée.

Effectivement, il n'y a pas 2 tailles d'alertes mais XWiki prévoit une version plus petite d'une alerte pour l'utilisation d'une macro alerte 'inline' - dans un paragraphe avec du texte - ainsi:
![image](https://user-images.githubusercontent.com/657716/169090134-aec77d6b-f505-4793-a4ee-5de71698e0c9.png)

Une première observation est que le style courant n'est pas correct pour ce cas, mais ce n'est pas vraiment grave car ce type d'alerte n'est pas utilisé dans l'observatoire.

On pourrait profiter de ce type d'alerte "plus petit", prévu par XWiki, pour appliquer le style alert-sm, et qu'a chaque fois qu'on a besoin d'une telle alerte sm on va devoir forcer le fait d'avoir du markup 'en ligne'.

J'ai fait un essai:
![image](https://user-images.githubusercontent.com/657716/169090417-1523094b-cd2f-4847-9d66-e8b9a9975406.png)
par contre le résultat n'est pas du tout equivalent aux messages standard XWiki, car il n'est pas vraiment 'inline': il s'affiche toujours tout sur la même ligne (et passe à la ligne s'il y a pas assez de place sur la ligne), car il utilise 'inline-block'.

**Comment by lucaa** [comment]
Sinon, @ClemDee de ce que je vois dans le dsfr, les alertes non-sm sont les alertes avec des titres. Par contre, il n'est pas clair si le titre est obligatoire ou pas, en lisant https://gouvfr.atlassian.net/wiki/spaces/DB/pages/736362500/Alertes+-+Alerts ça à l'air, plus ou moins.
Dans bootstrap/XWiki, les alertes n'ont pas de titre ou autre contrainte sur le contenu, il faut l'ajouter dans le markup. Ainsi, je me demande si les alertes que tu as implémenté pour ce ticket existent vraiment du point de vue du dsfr, et s'il ne serait pas plus sage d'implémenter les alertes sm par défault, laissant les alertes md à implémenter custom.

Pour les alertes md on pourrait utiliser la macro box de xwiki, qui fait une well et qui, contrairement aux macros warning/error/info/success, à un paramètre permettant d'ajouter une classe CSS.
Ainsi, on pourrait reserver le markup suivant pour les alertes md - exemple pour un warning
```
{{box cssClass="warningmessage alerte-md"}}
....markup pour le contenu, avec titre ou pas...
{{/box}}

**Comment by ClemDee** [comment]
> Dans bootstrap/XWiki, les alertes n'ont pas de titre ou autre contrainte sur le contenu, il faut l'ajouter dans le markup.

Je vois ce que tu veux dire, mais c'est à peu près la même chose du coté du dsfr. Rien dans le markup n'oblige à mettre un titre, c'est la spec dsfr qui impose d'inclure un titre (via une classe `fr-alert__title`, ou via un titre de `h2` à `h6`). C'est à nous d'écrire le markup (dsfr ou bootstrap/XWiki) afin qu'il respecte la spec. Du coup rien ne nous empèche d'utiliser un titre à l'intérieur du markup bootstrap/XWiki afin que l'alerte soit dsfr compliant.

> Ainsi, on pourrait reserver le markup suivant pour les alertes md, en ajoutant des styles pour la classe .alerte-md

C'est des classes sémantiques qui existent déjà quelque part dans boostrap / XWiki, ou alors ça nous ferait créer des classes customs ? Dans le deuxième cas je serais pas très chaud, implémenter nous propres classes sémantiques dans le but de styliser des composants boostraps / XWiki en tant que composants dsfr ça va être incompréhensible à la fin.

> par contre le résultat n'est pas du tout equivalent aux messages standard XWiki, car il n'est pas vraiment 'inline': il s'affiche toujours tout sur la même ligne (et passe à la ligne s'il y a pas assez de place sur la ligne), car il utilise 'inline-block'.

Je vois pas vraiment le comportement attendu des messages standards inlines XWiki, je pourrais regarder ça quand j'en aurais le temps si tu veux.

**Comment by ClemDee** [comment]
> C'est à nous d'écrire le markup (dsfr ou bootstrap/XWiki) afin qu'il respecte la spec.

Je me rend compte qu'en fait c'est totalement infaisable, car les messages d'alerte existants eux n'auront pas de titres et du coup seront incorrects, et certaines alertes du mockup ne possèdent pas forcement de titre non plus. Du coup tu as raison je vais mettre la taille en sm par defaut.

Après une chose qui peut se faire c'est d'adapter les marges de l'alert suivant la présence ou non d'un titre `h2`-`h6` à l'interieur, mais faut voir si ça rend pas l'implem et l'utilisation de ce alertes trop compliquée.

**Comment by ClemDee** [comment]
Transformation du style des alertes par default en taille small

**Comment by lucaa** [comment]
> D’où ma proposition d'ajouter cette nouvelle classe dans le color thème DSFR, pour que l'ajout d'une telle boite reste simple pour l'utilisateur, en utilisant juste une syntaxe différente. 

Mais c'est pas du tout urgent, de ce que je me rappelle on n'a pas encore besoin pour l'observatoire. On va le faire lorsque le premier besoin se présente.

**Comment by lucaa** [comment]
> C'est des classes sémantiques qui existent déjà quelque part dans boostrap / XWiki, ou alors ça nous ferait créer des classes customs ? 

Ces classes n'existent pas dans XWiki.

> Dans le deuxième cas je serais pas très chaud, implémenter nous propres classes sémantiques dans le but de styliser des composants boostraps / XWiki en tant que composants dsfr ça va être incompréhensible à la fin.

Si la peur de l’incompréhensibilité est liée au nom dsfr de cette classe, on peut tout à fait choisir un autre nom de classe. Sinon je ne vois pas de problème d'ajouter une couche d'"API" CSS dans un thème de couleurs personnalisé, tant que c'est correctement documenté je ne vois pas de problème (et si je ne me trompe pas on le fait déjà - ou on le faisait - pour l'observatoire pour quelques éléments fréquents - une taille de texte, le marqueur de champs obligatoire, etc).

**Comment by ugodtn** [comment]
Ok pour ce que j'ai pu voir, je valide.
