### ISSUE TITLE
L'ordre des démarches dans la section "suivre vos démarches" pour un utilisateur connecté n'est pas claire

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1120]
Sur la page d'accueil, la liste des démarches est affichée pour le porteur (implémentée dans #1053), mais l'ordre de ces démarches dans la liste n'est pas claire, ce n'est pas l'ordre alphabétique par titre, ni l'ordre de la création ou modification des démarches, ni l'ordre des identifiants.

![image](https://user-images.githubusercontent.com/657716/167424834-61418f76-8f14-4a8c-a075-bdceba13cf7d.png)

Peut-être que la plus facile à comprendre pour l'utilisateur est l'ordre alphabetique des noms.

**Comment by lucaa** [comment]
@ugodtn : un avis sur la bonne ordre à utiliser?
L'affichage du mockup à https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=613%3A54250 semble compatible avec l'ordre alphabétique des noms.

**Comment by AnthonyBrunelli** [comment]
Vu ce jour avec Anca et Ugo: mettre l'ordre alphabétique.

**Comment by lucaa** [comment]
L'ordre alphabetique a été mise en place.

**Comment by lucaa** [comment]
Oui, il y a effectivement une distinction, les minuscules sont à la fin, c'est un effet de bord du tri fait lors de la requête dans la base.

Si on considère que c'est un cas qui peut arriver avec des données réelles, je peux changer l'implémentation pour faire le tri en post processing. Par contre, si on veut un comportement complet qui couvre tout, il faudrait aussi ignorer les accents au tri, j'imagine?

**Comment by ugodtn** [comment]
@lucaa Oui, c'est souhaitable, et effectivement il faut aussi ignorer les accents dans ce cas !
