### ISSUE TITLE
Mise en place / uniformisation de la marge entre le header et le début du contenu (titre de la page)

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1121]
Lors des différentes implémentations UI/UX et suite à #1035 , la marge en haut de la page entre le header et le début du contenu est pas du tout claire et est hétérogène, aussi entre le mode visualisation et édition.
L'objectif d'espacement est celui des mockups sur figma, e.g. https://www.figma.com/file/kG2znZqEzySDPUxiWbrEme/JDMA?node-id=611%3A56809 .

Quelques exemples:
* une page de contenu / d'aide:
![image](https://user-images.githubusercontent.com/657716/167428861-3c0c14ff-46d0-4ce0-8e93-702840d6c0be.png)
* page de la démarche, en mode visualisation et édition:
![image](https://user-images.githubusercontent.com/657716/167428789-e8d51b77-d888-42eb-b6b3-c38179717688.png)
![image](https://user-images.githubusercontent.com/657716/167428808-cbfb01ec-d718-411a-ba8f-a500145f60f0.png)
* formulaire d'ajout de la nouvelle démarche
![image](https://user-images.githubusercontent.com/657716/167428735-e3c83899-f44c-428a-837b-1b34c425caf8.png)
* page de connexion
![image](https://user-images.githubusercontent.com/657716/167428714-47eeae78-307d-4e4b-ae01-95bff355bc32.png)

Note: le fil d'Ariane, pour les utilisateurs qui en ont (admin Dinum), peut-être placé directement sous le header, si nécessaire (le DSFR peut être consulté aussi, pour réference), mais aussi avec un espace, en fonction de la solution choisie.
Le profil visé par cette tâche est le profil porteur / admin ministeriel.

Note: ces modifications ne doivent avoir aucun impacte sur le formulaire d'avis qui a été implémenté et mesuré précisément pour correspondre à son mockup.

**Comment by lucaa** [comment]
L'espacement avec le message implémenté pour #1093 doit être aussi vérifié lors de l'implémentation de ce ticket.

**Comment by lucaa** [comment]
Affichage mobile à vérifier et à implémenter aussi.

**Comment by lucaa** [comment]
à valider, à chaque changement, les écrans "spéciaux" qui ne sont pas visés par cette tâche mais qui ne doivent pas souffrir des régressions suite à ce travail:
* page d'accueil
* page de présentation du produit JDMA
* page observatoire
* formulaire d'avis.

**Comment by ClemDee** [comment]
Le haut de page est désormais correctement espacé par rapport au header.
Cela s'applique pour : 
- pages de contenu / d'aide
- pages de démarche
- pages de connexion / inscription
- pages d'édition inline / wiki / object / class

Les marges sont responsives, et s'adaptent à la présence d'une boite de message en haut de la page, ainsi que des breadcrumbs.

Les pages spéciales (Main, JDMA, Obvservatoire, formulaire d'avis) n'ont pas subi de régression.

**Comment by lucaa** [comment]
Je rouvre pour répondre au commentaire ici https://github.com/DISIC/observatoire/commit/0c25e09bdfdc4da4350e62a3f5f1ba2b32efd4e3#r75445951  (une modification fait pour ce ticket change un comportement définit ailleurs).

**Comment by ClemDee** [comment]
@lucaa J'ai séparé les styles totemize des styles de l'uniformisation de la marge du haut de page comme convenu.
