### ISSUE TITLE
Remplacer "Support accessible" par "Aide joignable"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1122]
En lien avec #1115

- Dans l'Observatoire (intitulé de colonne)
- Sur la page de description des critères

[note: voir si ça apparaît autre part: Anca tu as une fonctionnalité pour faire ça non?]

**Comment by ClemDee** [comment]
"Support accessible" a été remplacé par "Aide joignable" pour chacune de ses occurrences dans le wiki.
