### ISSUE TITLE
Simplification de l'inclusion des polices DSFR

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1128]
Apparemment, suite à 2 travaux successifs qui impliquent les polices DSFR, on s'est retrouvé avec 2 endroits ou les polices DSFR sont définis et stockés:
* une fois dans le SSX Fonts.DSFRWebfontSSX , qui utilise des polices du répertoire dsfr sur disk et est inclus à partir du skin - fait pour #1010
* une deuxième fois dans Demarches.Code.DSFRTheme, qui utilise des pièce jointe du thème DSFRTheme, et est configuré pour être activé partout sur le wiki - fait pour #1051 .

Il n'y a pas de raison d'en avoir 2 fois la même chose, un devrait être enlevé.

**Comment by ClemDee** [comment]
La page `Fonts/DSFRWebfontSSX` a été supprimée.

Les polices dsfr (Marianne et Spectrale) sont les même entre la version 1.1.0 et la 1.3.1 du dsfr, la diff de leur mise à jour dans le DSFRTheme est donc nulle.
