### ISSUE TITLE
Foires aux questions à remplir avec les contenus pour la production

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1131]
Lors de l'implémentation des tâches #1048 et #1094 , deux nouvelles sections de contenus / documentation / explications ont été ajoutées:
* la Foire aux questions du bas de la page de présentation du produit JDMA
* les questions / réponses du bas de l'onglet JDMA de la démarche.

Il faut préparer les réponses aux questions et soit les fournir pour qu'elles soient remplies directement lors de la livraison en production, soit les remplir directement en production une fois la version 4.10 livrée.

**Comment by lucaa** [comment]
Les pages où les textes doivent être complétés seront disponibles dans la section "Pages de textes explicatifs" de la zone "outils d'administration" pour les admins dinum.

**Comment by AnthonyBrunelli** [comment]
Vu avec Anca&Ugo, solliciter aussi avec Joffrey.
