### ISSUE TITLE
Sur les petits écrans, si le texte du bouton ne rentre pas sur une seule ligne, le bouton doit passer à 2 lignes

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1133]
<img width="294" alt="Capture d’écran 2022-06-03 à 11 15 40" src="https://user-images.githubusercontent.com/34340568/171826072-aba43f2d-b0e1-408c-82cb-dcc13607ce32.png">

**Comment by ClemDee** [comment]
Fixé sur la page Main.
J'ai vérifié pour la page JDMA, il ne devrait pas y avoir de problème similaire (texte de boutons beaucoup plus courts)

**Comment by ClemDee** [comment]
On ne va pas implémenter ça plus globalement car la règle `whitespace: nowrap` est appliquée sur la classe `.btn`, utilisée dans tout le wiki, ce qui pourrait casser des layouts existants.
