### ISSUE TITLE
Marge blanche trop importante en dessous du hamburger du menu principal sur mobile

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1135]
<img width="293" alt="Capture d’écran 2022-06-03 à 11 25 00" src="https://user-images.githubusercontent.com/34340568/171827728-440f65a4-f893-4f9b-8698-b2bfb6370212.png">

**Comment by lucaa** [comment]
à regarder avec #952 , pour faire les modifications du header une seule fois.

**Comment by lucaa** [comment]
Comme ce ticket n'est pas bloquant, et comme il vaut mieux le regarder avec #952 , je deplace ce ticket dans 4.11.

**Comment by lucaa** [comment]
> sur mobile

en fait ça n'arrive que sur les mobiles très petits.

**Comment by lucaa** [comment]
à vérifier s'il y a une taille minimale acceptable dans le dsfr.

**Comment by AnthonyBrunelli** [comment]
@ugodtn c'est pour oit! Testable en staging

**Comment by ugodtn** [comment]
OK pour moi !
