### ISSUE TITLE
Changements sur la page d'accueil

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1137]
Nouveau visuel à obtenir (mode deconnecté):

![image](https://user-images.githubusercontent.com/34340568/171829408-8fa3d517-3a49-46ee-8d4b-956658594754.png)

Changements (mode deconnecté):
* suppression des textes de la section "Comment evaluons nous..." et adaptation de la tailles des cartes en conséquence
* bloc titre:
  * nouvelle taille du h1: 3em (uniquement desktop)
  * rétrécissement de la taille du titre pour qu'il passe sur 2 lignes (48rem - pas des colonnes mais des rems)
* changement des couleurs des bloc (inversement de l'alternance)
  * attention: l'accueil connecté doit suivre

**Comment by lucaa** [comment]
couleurs de l'accueil connecté:
* le titre n'est plus affiché du tout
* rechercher une démarche: fond blanc
  * à ajouter le style DSFR sur la boite de recherche pour avoir le contour
* suivre vos démarches: pas de changement
* administrez les données: remonte juste en dessous de suivre vos démarches et devient blanc
* les 250 démarches suivies: devient gris (le gris des questions)
* "des questions" il devient blanc comme sur la PA non-connecté

**Comment by ugodtn** [comment]
Capture des infos ci-dessus : 
![image](https://user-images.githubusercontent.com/34340568/171831297-dc94ed9a-4d64-442a-9da6-a483dbcb19c7.png)

**Comment by ClemDee** [comment]
Tous les changements ont été effectués.

**Comment by lucaa** [comment]
Je rouvre ce ticket car suite à la modification

> le titre n'est plus affiché du tout 

on a un problème de cohérence de la hiérarchie de titres (critère RGAA).

Le titre H1 de la page d'accueil est celui de la section titre. Ainsi, après modifications, nous avons des h2 orphelins:
![image](https://user-images.githubusercontent.com/657716/173034814-f0487048-4792-4b18-a6bf-4cb2a5d1d082.png)

**Comment by lucaa** [comment]
vu avec @ugodtn : la nécessité d'enlever le titre h1 de la page devient:
* on change le titre en 'Mon tableau de bord'
* la section du titre fusionne avec la section suivante, "rechercher une démarche" (dont le nom change aussi en "rechercher une démarche existante")
* le titre "rechercher une démarche" ne sera plus un titre niveau 2, mais un bloc dont le style visuellement est le même que le h4.

**Comment by ClemDee** [comment]
Tous les changements ont été appliqués : 
* titre changé en 'Mon tableau de bord'
* section du titre fusionnée avec la section "rechercher une démarche"
* renommage "rechercher une démarche existante"
* le titre "rechercher une démarche" n'est plus un titre h2, mais un texte avec le sytle h4 (implémentation des styles `.h1` - `.h6` dans le DSFRTheme).

**Comment by ugodtn** [comment]
@lucaa Ok pour les modifications, mais j'observe un bug sur mobile : l'icône du bouton de recherche sort de son cadre :
<img width="320" alt="Capture d’écran 2022-06-20 à 12 24 41" src="https://user-images.githubusercontent.com/34340568/174582158-9d0ae2e6-1566-4e53-9ffc-f534af976cff.png">

**Comment by lucaa** [comment]
Ticket créé pour ce nouveau problème, au #1157 .
