### ISSUE TITLE
Modifications PA connecté

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1138]
1/ le lien "Comment ça marche" -> icône à déplacer avant le lien
2/ le bloc "des questions" : remplacer le "retouvez-nous sur twitter" avec le même bouton "contactez-nous" de la page JDMA (en bas)
3/ bloc "suivre vos démarches" le bouton "créer une nouvelle démache" doit passer à ligne  - avec un marge d'un rem.
<img width="1231" alt="Capture d’écran 2022-06-03 à 11 53 14" src="https://user-images.githubusercontent.com/34340568/171832240-21af62bb-2797-463a-aed7-74f8c8f02661.png">

**Comment by lucaa** [comment]
@ClemDee il y a un autre ticket pour ça: #1142, je te l'ai assigné.

**Comment by ClemDee** [comment]
Le lien de contact a été mis à jour dans #1142, travail terminé.
