### ISSUE TITLE
La page JDMA doit avoir une largeur de 10/12 colonnes

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1139]
si on considère que la largeur du header represente 12 colonnes, la taille du contenu de la page JDMA soit être de 10 colonnes sur 12 - voir maquette figma.

Aujourd'hui ça a été implémenté pour #1048 avec 12/12 colonnes.

**Comment by ClemDee** [comment]
La page de JDMA fait maintenant 10 colonnes de large pour la taille desktop
