### ISSUE TITLE
Page JDMA : éléments non-conformes à la maquette

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1140]
* le titre "comment suivre la satisfaction..." doit être un H1
* Section comment à récolter:
  * espace blanc entre le titre et le bloc
  * cercle blanc autour des numéros
  * contrairement au style DSFR correspondant, les blocs / cartes ne doivent pas avoir de bordure grise (voir la maquette)
  * la couleur de fond des blocs doit être celle des 'tile' DSFR accentués (fr-tile-grey), #EEEEEE
  * le bouton "commencer" est un bouton grand (comme celui de la PA voir #1137 )
* les badges "Gratuit", "RGAA" et "RGPD":
  * trop arrondis: l'arrondi par rapport à la taille verticale du badge doit etre de 24/64 (cf tailles de figma) mais la taille du badge doit rester variable avec la taille du texte
  * le texte n'est pas centré verticalement. C'est potentiellement un problème de la police Marianne qui n'a pas la baseline au bon endroit, mais il faut corriger. Soit en prenant la police Marianne de la dernière version de DSFR soit en ajustant à la main.
* bloc questions: 
  * marge blanche en dessous petite par rapport à la maquette
  * point d'interrogation dans le titre au lieu d'exclamation
  
Aussi: vérifier que les espaces avant les points d'interrogations sont tous insécables.

**Comment by ClemDee** [comment]
Modifications effectuées.

**Comment by lucaa** [comment]
Note: la police Marianne n'a pas été mise à jour dans le cadre de ce ticket, elle sera mise à jour lors de la prochaine mise à jour du DSFR. Ainsi, comme les badges "gratuit, RGAA et RGPD" ont été mises à jour manuellement pour compenser les pbs de baseline de Marianne, lors de la mise à jour de la police, ces badges seront à re-travailler.

**Comment by ugodtn** [comment]
@lucaa ok pour les modifications, mais je vois un soucis sur mobile : les marges aux niveaux des badges ne respectent pas la maquette (on dirait que chaque texte est rattaché au badge du dessous) :
<img width="320" alt="Capture d’écran 2022-06-20 à 12 31 30" src="https://user-images.githubusercontent.com/34340568/174583211-adfb65c6-689b-4e36-85dc-544e3b16af17.png">

**Comment by ugodtn** [comment]
@lucaa Par ailleurs, je me rends compte que, sur mobile, le titre h1 est aligné à gauche alors qu'il devrait être centré.

**Comment by ugodtn** [comment]
@lucaa Et tant qu'à faire, est-ce que l'on peut faire une petite modification de texte ? Cela concerne les étapes en haut, en particulier l'étape 4 pour laquel il faudrait utiliser le texte suivant : "Retrouvez les avis et leur analyse sur la page de votre démarche."

**Comment by lucaa** [comment]
J'ai créé #1155 pour ces 2 correctifs et modification.
