### ISSUE TITLE
Page JDMA: images à re-travailler

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1141]
La qualité des images est à reverifier et à remplacer. Images à fournir par @ugodtn .

Les ombres des images sont "coupées" en version mobile.
<img width="318" alt="Capture d’écran 2022-06-03 à 12 41 15" src="https://user-images.githubusercontent.com/34340568/171839214-edfaa9be-18c9-4b76-bc64-1b6b9babedfa.png">
~~Ainsi, il faudra implémenter l'ombre en CSS pour pouvoir la désactiver en mobile.~~
Les images sans ombres à fournir par @ugodtn .

**Comment by kamalcon** [comment]
![image 21](https://user-images.githubusercontent.com/14159449/172573918-9213f3a2-fa52-4c37-bf72-bd977ee87085.png)
Hello Anca,
Voici une version sans ombres. C'est que cette image la ? Il y a d'autres images avec ce problème ?

**Comment by ugodtn** [comment]
+ @lucaa peut-on supprimer les ombres sous les autres images, celles des quatre blocs ? Merci !

**Comment by ugodtn** [comment]
Voici l'image du header en SVG :
![Mobile](https://user-images.githubusercontent.com/34340568/173046088-17a7e614-9f94-4c31-9558-ccd6ac2a3d63.svg)

**Comment by lucaa** [comment]
finalement, après discussions, à faire:
* enlever les ombres de toutes les images sauf la première;
* remplacer la première image avec sa version HQ en svg ci-dessus;
* réparer les règles CSS pour avoir l'ombre qui ne soit pas coupé.

**Comment by kamalcon** [comment]
![illustration 2](https://user-images.githubusercontent.com/14159449/173548649-805dda3c-fb57-4fca-a66c-09e834e90de0.svg)
![illustration 3](https://user-images.githubusercontent.com/14159449/173548659-7761eaa9-4f26-409c-86b4-fbf0509a9273.svg)

Voici les deux images legerment retravaillé (après discussion avec Ugo) à remplacer.

**Comment by ClemDee** [comment]
> Voici l'image du header en SVG : ![Mobile](https://user-images.githubusercontent.com/34340568/173046088-17a7e614-9f94-4c31-9558-ccd6ac2a3d63.svg)

@ugodtn La police utilisée sur cette version de l'image n'est pas Marianne et le texte est coupé à droite, j'imagine que ce n'est pas voulu ?

**Comment by ClemDee** [comment]
Tout a été fait sauf le remplacement de la première image par sa version HQ, j'attends la réponse de @ugodtn à mon message précédent.

**Comment by lucaa** [comment]
Cette image semble contenir un `<text>` avec la police Marianne spécifiée alors que les autres SVGs de ce ticket contiennent des paths. J'imagine que cette transformation a été oubliée pour cette image?

**Comment by ugodtn** [comment]
@ClemDee @lucaa je vous refais un export sans balise <text> pour ne pas être dépendant de la typo.

**Comment by ClemDee** [comment]
L'image du header a été remplacée par sa version HQ, il ne reste plus rien à faire sur ce ticket

**Comment by ugodtn** [comment]
@lucaa désolé mais il y a un soucis dans une ombre dans l'image tout en haut. Ce n'est pas de votre faute, l'image fonctionne comme il faut de mon côté sur sketch mais l'export doit être mauvais. J'ai pensé que c'était juste un bug de git. Bref, voici une nouvelle image, à utiliser :
![JDMA](https://user-images.githubusercontent.com/34340568/175334926-916f676f-32e6-40bf-a6ce-dc52188f9433.svg)

**Comment by lucaa** [comment]
Je rouvre ce ticket pour re-mettre à jour.

**Comment by ClemDee** [comment]
L'image a été mise à jour

**Comment by kamalcon** [comment]
On a encore retravaillé les images, à remplacer :
![illustration 1](https://user-images.githubusercontent.com/14159449/176919112-0a8d603b-8f5e-49d2-bfd4-fb8718f21f45.svg)
![illustration 2](https://user-images.githubusercontent.com/14159449/176919116-28c51fd0-bad8-43b3-9a06-1902b5ca8a1b.svg)
![illustration 3](https://user-images.githubusercontent.com/14159449/176919119-c37e605c-fab3-4663-8812-7fd33d1177f3.svg)
![illustration 4](https://user-images.githubusercontent.com/14159449/176919123-7267e18c-13ff-48b8-8124-a17cd7ba7b4b.svg)
.

**Comment by lucaa** [comment]
Évitons de rouvrir de tickets des versions _fermées et installées en production_, ça met un peu de chaos dans le suivi des modifications de la production (car la moitié de la tâche est en fait faite et livrée alors que l'autre moitié - ce nouveau commentaire -  ne l'est ni l'un ni l'autre. La tâche, dans sa totalité, est alors à la fois faite et pas faite, donc difficile à tracer).

Je crée une nouvelle tâche pour ce travail - #1172 - et je referme celle ci car le travail initialement prévu et inclus dans 4.10 a été fait et livré avec 4.10.
