### ISSUE TITLE
Taille et position des titres des pages de connexion et d'inscription non-homogènes 

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1143]
Connexion: titre plus petit et plus bas
Inscription: titre plus grand et plus haut.

à rendre cf. à la maquette, de préference (h1).

**Comment by ClemDee** [comment]
Le layout sous forme de panel de la page de login a été modifié afin de l'aligner avec la page d'inscription.

**Comment by ugodtn** [comment]
@lucaa Par ailleurs, il y a un bug lorsque l'on vient de la page JDMA, que l'con clique sur un bouton Commencer. Alors, il y a deux titres :
<img width="1280" alt="Capture d’écran 2022-06-20 à 12 12 47" src="https://user-images.githubusercontent.com/34340568/174580083-748a129e-9428-4dd1-b169-a91d69aa7606.png">

**Comment by lucaa** [comment]
> @lucaa Les deux ne sont pas encore parfaitement en phase, cf. images ci-dessous (sur mobile, car c'est plus facilement visible) :

Apparemment c'est uniquement sur staging, sur dev ce n'est pas le cas. à vérifier si c'est un nouveau ticket ou juste un problème de serveur.

**Comment by lucaa** [comment]
> @lucaa Par ailleurs, il y a un bug lorsque l'on vient de la page JDMA, que l'on clique sur un bouton Commencer. Alors, il y a deux titres : <img alt="Capture d’écran 2022-06-20 à 12 12 47" width="1280" src="https://user-images.githubusercontent.com/34340568/174580083-748a129e-9428-4dd1-b169-a91d69aa7606.png">

Ticket créé, #1156.

**Comment by lucaa** [comment]
> > @lucaa Les deux ne sont pas encore parfaitement en phase, cf. images ci-dessous (sur mobile, car c'est plus facilement visible) :
> 
> Apparemment c'est uniquement sur staging, sur dev ce n'est pas le cas. à vérifier si c'est un nouveau ticket ou juste un problème de serveur.

ticket créé, #1158 .
