### ISSUE TITLE
Page observatoire: lien données ouvertes sur data.gouv ne doit pas être souligné

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1145]
![image](https://user-images.githubusercontent.com/657716/171843710-4ffcaaf8-895f-433e-9e43-fcc6b7ba73ca.png)

**Comment by ClemDee** [comment]
Fixé.

**Comment by ugodtn** [comment]
@lucaa ok pour le soulignement. Je remarque que le lien n'est pas bon cependant, c'est parce que l'on se trouve sur staging ?

**Comment by lucaa** [comment]
> @lucaa ok pour le soulignement. Je remarque que le lien n'est pas bon cependant, c'est parce que l'on se trouve sur staging ?

Oui.
