### ISSUE TITLE
Rendre les onglets de la page de la démarche accessibles

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1149]
Les onglets de la page de la démarche doivent être accessible du pdv RGAA.

**Comment by lucaa** [comment]
Audit à faire.

**Comment by AnthonyBrunelli** [comment]
Tout est là : https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-automatic.html

à l'heure actuelle, possibilité de passer d'un onglet à l'autre par tab, mais problème si on rentre dans une page. La navigation entre onglet doit se faire par les flèches (et autres précisions dans le liens ci-dessus).

**Comment by ClemDee** [comment]
Il manquait quelques attributs sur les onglets des panels (notamment `role="tab"` et `data-toggle="tab"`) que j'ai rajouté.

Cependant cela ne change en rien le fait que le comportement des onglets décris par la spec w3.org n'est pas du tout implémentée par bootstrap, qui se contente juste de rendre les onglets focusable via la touche Tab. J'ai donc implémenté le comportement décris par la spec via un jsx sur la page DemarchesSheet, désormais seulement l'onglet courant est focusable via "Tab", et le changement d'onglet se fait par les touches fléchées.
