### ISSUE TITLE
Regrouper les styles spécifiques pour le formulaire d'avis à un seul endroit

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1150]
Aujourd'hui il y a des styles pour des éléments du formulaire d'avis aux 2 endroits:
* dans Demarches.Code.DemarchesSheet, à côté d'autres styles qui s'appliquent à la page de la démarche et ses onglets
* dans Demarches.Code.DemarcheAvisFormTab, appliqué uniquement sur le formulaire d'avis

à priori, pour l'affichage d'un formulaire d'avis, il y a des règles de ces 2 ensembles de règles qui s'appliquent.

Il n'y a pas de raison d'avoir 2 endroits, maintenant qu'on a ajouté des styles spécifiques au formulaire d'avis il n'y a plus de raison d'avoir les règles au niveau de DemarchesSheet, il faut regrouper pour faciliter la maintenance.

**Comment by ClemDee** [comment]
Toutes les règles conernant le formulaire d'avis dans DemarchesSheet étaient soit overightées, soit plus d'actualités.
Elle ont donc été supprimées.
