### ISSUE TITLE
Le logo de l'observatoire est trop petit

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1154]
Avant:
![Selection_193](https://user-images.githubusercontent.com/657716/174679700-99b1c61b-2ef7-436f-9774-6bcdf3b1c60f.png)

Après:
![Selection_194](https://user-images.githubusercontent.com/657716/174679705-4d69864b-2e99-4c17-9fc1-f2c91eb8a0c1.png)

**Comment by lucaa** [comment]
@ClemDee je sais que t'as commencé sur #952 et je ne sais pas si ceci est un effet de bord de ce début de travail ou un autre problème.
En tout cas, pour la 4.10 il faudra rester sur du logo image et le restaurer à sa taille précédente.

**Comment by ClemDee** [comment]
En effet le problème venait que certaines modifications du nouveau header avaient été committées dans #1121, j'ai revert et recommitté les changements proprement. Cependant je n'ai pas vraiment la possibilité de tester sur dev que le problème a bel et bien été fixé, vu que le header a totalement changé entre temps.
