### ISSUE TITLE
L'icône du bouton de recherche de la PA connecté passe à la ligne sur les petits écrans

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1157]
![image](https://user-images.githubusercontent.com/657716/174682021-69851e0e-c9b6-45d0-9ae4-fc3de09d0d77.png)

**Comment by lucaa** [comment]
Il semble que le comportement est lié au formattage du HTML de ce bouton (?): comme le contenu du bouton est un contexte inline et que les contenus sont inline (span) les retours à la ligne sont relevants car ils introduisent des éléments texte / whitespace dans le html (mais qui bizarrement ne prennent pas de place quand affichés à l'écran?) Soit il y a un moyen de prevenir ce comportement par le CSS (l’interprétation des retours à la ligne de la source HTML comme du contenu text) soit il faut mettre à jour le HTML pour éviter ce formattage.

**Comment by ClemDee** [comment]
Fixed. C'était dû à la modification effectuée dans #1133.
