### ISSUE TITLE
La page d'inscription contient une ligne d'espace blanc de trop au dessus du titre

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1158]
Voir les écrans dans https://github.com/DISIC/observatoire/issues/1143#issuecomment-1160247490 .

L'espace de trop est un `<div class='wikimodel-emptyline' />` .

**Comment by lucaa** [comment]
Note: le bug n'est pas présent sur le serveur de développement.
@ClemDee il semble y avoir des modifications dans XWiki.Registration sur le serveur de dev qui ne sont pas committées et dont l'effet est compatible avec ce type de ligne d'espace blanc...

**Comment by ClemDee** [comment]
Fixé

**Comment by ClemDee** [comment]
> @ClemDee il semble y avoir des modifications dans XWiki.Registration sur le serveur de dev qui ne sont pas committées et dont l'effet est compatible avec ce type de ligne d'espace blanc...

Le problème ne venait pas des modifications non commitée, d'ailleurs les `##` rajouté sur certains lignes vides doivent venir de moi, par contre je ne me souviens pas avoir modifié les deux premières lignes 
```diff
-    $xwiki.get('jsfx').use('uicomponents/widgets/validation/livevalidation_prototype.js')
-    $xwiki.get('ssfx').use('uicomponents/widgets/validation/livevalidation.css', true)
+    #set ($discard = $xwiki.get('jsfx').use('uicomponents/widgets/validation/livevalidation_prototype.js'))
+    #set ($discard = $xwiki.get('ssfx').use('uicomponents/widgets/validation/livevalidation.css', true))
```
Tu as une idée du ça viendrait ?
