### ISSUE TITLE
Remplacer le "mailto" du contact

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1171]
Le "mailto" est à proscrire - c'est ce qu'on dit aux administrations, donc c'est d'autant plus important de respecter ce point.

**Comment by AnthonyBrunelli** [comment]
Pour le mailto c'est "Les adresses électroniques cliquables (attribut « mailto ») sont interdites pour des raisons de sécurité et de compatibilité avec le poste de travail de l’utilisateur"

Pour la forme que ça doit prendre, il y a un travail interministériel en cours (ie. pas encore  fini...). De notre côté, deux possibilités:
- soit le formulaire que tu nous as montré est facile à adapter et on va partir de ça;
- soit ça n'est pas le cas et on va faire une page simple qui indique notre mail de contact.
@ugodtn si tu veux compléter...

**Comment by lucaa** [comment]
@AnthonyBrunelli :+1: , merci pour la réponse.

Y-a-t-il des indications liées au suivi de ces formulaires de contact? Par exemple: 
* faut-il que l'utilisateur puisse retrouver sa demande plus tard?
* est-ce qu'une adresse d'email de la part de l'utilisateur est obligatoire dans le formulaire (pour assurer le suivi) ou on laisse ce champs optionnel mais on averti que si l'adresse n'est pas remplie il n'y aura pas de réponse possible?
* j'imagine que la plupart du temps un email est envoyé aux responsables du site suite au remplissage de ce formulaire par l'utilisateur. Faut-il envoyer une copie de l'email à l'utilisateur?
* si une copie est envoyé à l'utilisateur qui fait la demande de contact, y-a-t-il des restrictions/recommandations liées à l'affichage de l'adresse de contact du site à l'utilisateur?

**Comment by AnthonyBrunelli** [comment]
@lucaa Dans l'ordre des points : 

- Pas besoin.
- On rend obligatoire (c'est un mail de contact).
- Nous mettrons plutôt en place une réponse automatique au niveau de notre boîte mail.
- Pas bien compris : l'adresse de contact est celle qu'il a utilisé pour écrire non? Je ne vois pas l'enjeu de lui masquer - mais je pense que le point précédent répond à la question.

(on est d'accord que pour l'instant, tu nous dis juste la faisabilité en fonction de ça, pas de développement pour le moment, on travaille sur le sujet)

**Comment by AnthonyBrunelli** [comment]
Pas besoin de formulaire, on va faire une page simple. @ugodtn on tranche ça début de semaine prochaine?

**Comment by AnthonyBrunelli** [comment]
@lucaa @ClemDee voilà pour la page de contact : https://www.sketch.com/s/8c053adc-f9f5-4944-b4db-679e50787126
Normalement, pas d'excentricité :)
Si vous voyez quoique ce soit, vous nous dites !

**Comment by lucaa** [comment]
@AnthonyBrunelli y-a-t-il une préference pour l'URL de cette page?

**Comment by lucaa** [comment]
@ClemDee pistes techniques:
La page de la maquette n'a pas le titre à l'endroit habituel, il faudra donc trouver une solution pour cacher le titre standard de la page. 
Je propose d'utiliser une page avec une stylesheet extension spécifique pour cette page et cacher le titre à partir de la couche CSS spécifique. Vérifie quand même rapidement si cette approche convient du point de vue de l'accessibilité.

**Comment by lucaa** [comment]
@AnthonyBrunelli @ugodtn j'aurais besoin de 2 informations supplémentaires:
1/ quelle est la proportion entre les 2 colonnes en pour les tailles > 768px ? Il me semble que c'est 60% à gauche et 40% à droite  mais j'aurais besoin d'une confirmation...
![image](https://user-images.githubusercontent.com/657716/181512147-a70f7233-6f5c-4b56-af91-2fd5ba04a7ae.png)

2/ l'image de droite, telle que j'ai réussi à l'exporter de sketch en svg semble avoir un peu de pollution visuelle (des points, cercles et croix). Est-ce normal ou je devrais pouvoir obtenir autre chose? Pouvez-vous nous fournir le svg qui doit aller dans la page?
![Illustration](https://user-images.githubusercontent.com/657716/181512994-1ad31f43-2e90-407f-b1a1-1656de346426.svg)

![image](https://user-images.githubusercontent.com/657716/181512853-e2636287-bfe2-45d4-9ce4-c251fd8ddbf0.png)

**Comment by lucaa** [comment]
l'URL doit être observatoire.numerique.gouv.fr/contact .

**Comment by lucaa** [comment]
reste à faire:
* marge haute du texte "nous contacter" à revoir pour:
  * symétrie avec la marge basse
  * la marge haute sur mobile doit être la même que la marge entre le header et le titre des pages normales de texte (e.g. CGU)
* remplacement des autres liens mailto: page d'accueil et page JDMA (au moins)

**Comment by lucaa** [comment]
@AnthonyBrunelli @ugodtn en vérifiant tous les liens "mailto" de la plateforme je me rends compte qu'il y a encore un autre endroit ou on utilise un tel lien, sans que ça soit pour contacter l'equipe design.numerique.gouv.fr, c'est pour partager un observatoire par email:

![image](https://user-images.githubusercontent.com/657716/181796815-72babf5f-566b-4b29-ad07-dc3f89ab2d1d.png)

Que devrait-on faire avec ce lien?

**Comment by lucaa** [comment]
@AnthonyBrunelli @ugodtn aussi, juste pour confirmer, les liens de contact mailto aujourd'hui proposent l'envoi vers "**contact**@design.numerique..." . La page de contant propose sur la maquette propose l'envoi vers "**observatoire**@design.numerique... . Pouvez vous confirmer que le changement d'adresse de contact est bien voulu et pas juste un effet de bord?

**Comment by AnthonyBrunelli** [comment]
Oui c'est voulu!
Tu fais bien de demander  :)

**Comment by AnthonyBrunelli** [comment]
> @AnthonyBrunelli @ugodtn en vérifiant tous les liens "mailto" de la plateforme je me rends compte qu'il y a encore un autre endroit ou on utilise un tel lien, sans que ça soit pour contacter l'equipe design.numerique.gouv.fr, c'est pour partager un observatoire par email:
> 
> ![image](https://user-images.githubusercontent.com/657716/181796815-72babf5f-566b-4b29-ad07-dc3f89ab2d1d.png)
> 
> Que devrait-on faire avec ce lien?

Le supprimer :) (c'est juste pour le partage, ça n'est pas pour le contact)

**Comment by AnthonyBrunelli** [comment]
C'est bon pour moi Anca, tu peux passer en prod ! Merci :)

**Comment by lucaa** [comment]
> C'est bon pour moi @lucaa , tu peux passer en prod ! Merci :)

C'est fait, c'est en prod!

**Comment by AnthonyBrunelli** [comment]
Merci on regarde ça !

**Comment by AnthonyBrunelli** [comment]
C'est bon pour moi et pour Joffrey. @kamalcon si tu vois quelque chose, mets le là et je rouvre le ticket.
