### ISSUE TITLE
Images de la page de présentation du produit JDMA à mettre à jour

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1172]
cf https://github.com/DISIC/observatoire/issues/1141#issuecomment-1172434533 , les nouvelles images (pour une partie des sections) sont:

![illustration 1](https://user-images.githubusercontent.com/14159449/176919112-0a8d603b-8f5e-49d2-bfd4-fb8718f21f45.svg)
![illustration 2](https://user-images.githubusercontent.com/14159449/176919116-28c51fd0-bad8-43b3-9a06-1902b5ca8a1b.svg)
![illustration 3](https://user-images.githubusercontent.com/14159449/176919119-c37e605c-fab3-4663-8812-7fd33d1177f3.svg)
![illustration 4](https://user-images.githubusercontent.com/14159449/176919123-7267e18c-13ff-48b8-8124-a17cd7ba7b4b.svg)

**Comment by ClemDee** [comment]
Images mises à jour.

**Comment by lucaa** [comment]
@AnthonyBrunelli @kamalcon @ugodtn : cette modification est mise en place sur staging.
Elle pourra être livrée en production après votre validation.

**Comment by ugodtn** [comment]
C'est validé de notre côté @lucaa
