### ISSUE TITLE
Changer l'URL de la page JDMA

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1174]
Remplacer l'URL actuelle 
https://observatoire.numerique.gouv.fr/JDMA/
par
https://observatoire.numerique.gouv.fr/je-donne-mon-avis/

Faire en sorte que le lien fonctionne quelle que soit la casse (comme c’est le cas sur https://design.numerique.gouv.fr/design-NUMERIQUE/ par exemple)

À faire en priorité (j'ai l'impression que ce n'est pas une grosse tâche, mais il faut me dire dans le cas contraire :) )

**Comment by lucaa** [comment]
à faire uniquement la partie renommage.
le traitement de la casse sera fait dans une nouvelle tâche.

**Comment by ClemDee** [comment]
L'url de la page "JDMA" a bien été mise à jour en "je-donne-mon-avis"
Les références à cette page ont aussi été mise à jour dans tout le wiki.

**Comment by AnthonyBrunelli** [comment]
Salut @lucaa, ça va mieux ?
Tu sais quand est prévue la mise en prod ? @ClemDee peut-être ?

**Comment by lucaa** [comment]
@AnthonyBrunelli c'est fait, c'est installé en production (et en staging aussi), sensible à la casse pour l'instant. 

L'insensibilité à la casse sera mise en place par #1175 .

**Comment by AnthonyBrunelli** [comment]
Vu merci !
