### ISSUE TITLE
Alignement incorrect du texte dans sa boîte dans le message de succès de l'export des avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1177]
![image](https://user-images.githubusercontent.com/657716/180594994-2b12c3b9-6676-4ec4-afc4-25a366bd591d.png)

à vérifier aussi les autres messages possibles  au même endroit (avertissement, erreur).

**Comment by ClemDee** [comment]
Bad stylings were coming from an inline `<style>` tag injected by the Livetable Export Macro, which overrode styles from the Theme.
Fixed.
