### ISSUE TITLE
Alerte Pingdom

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#1186]
On a reçu des alertes pingdom de cette nuit (26/10). Des éléments sur ce sujet?

**Comment by AnthonyBrunelli** [comment]
![Annotation 2022-10-26 111140](https://user-images.githubusercontent.com/35567048/197985651-0ad81726-6c88-4a0e-a654-162bd161713e.jpg)

**Comment by AnthonyBrunelli** [comment]
Nouvelles alertes : 
![Annotation 2022-10-26 173238](https://user-images.githubusercontent.com/35567048/198070384-8289e825-8cba-47b6-8406-87cd5503957e.jpg)

**Comment by AnthonyBrunelli** [comment]
![image](https://user-images.githubusercontent.com/35567048/198287534-5c6de4f5-8c33-409a-8f38-74482a2fa41f.png)
Ce jour

**Comment by AnthonyBrunelli** [comment]
Nouveaux cas cet après-midi

**Comment by lucaa** [comment]
Après investigation, une partie de ces indisponibilités sont liées à des opérations d'export d'avis détaillés des démarches et une autre partie à la charge serveur générée par l'accès aux pages des graphes des démarches. La charge des graphes sera enlevée une fois #1180 déployé.

Un ticket opérations a été créé pour ce ticket, car c'est un problème d'opération plutôt qu'un problème de "produit".

Je ferme ce ticket maintenant, on pourra suivre les évolutions sur le ticket opérations.
