### ISSUE TITLE
Erreur à la production du javascript dans les logs serveur pour le javascript de la page de démarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1187]
Il semble que le code javascript ajouté pour #1149 affiche une erreur dans les logs côté serveur:

```
2022-11-14 18:57:04,232 [http://observatoire.numerique.gouv.fr/jsx/Demarches/Code/DemarchesSheet?language=fr&docVersion=35.13] WARN  c.x.x.w.s.SxDocumentSource     - Velocity errors while parsing skin extension [xwiki:Demarches.Code.DemarchesSheet] with content [/*
 * This script fixes keyboard navigation accessibility for bootstrap tabs
 * It provides 'ArrowLeft', 'ArrowRight', 'Home' and 'End' key navigation
 * It also make only the current tab focusable using tabindex,
 * and makes tab panel focusable too
 */
require(['jquery'], function($) {
  'use strict';

[...]

});]: 
```

mais sans que cela impacte le fonctionnement du code.

Le fait que cette erreur est affichée à chaque fois que le contenu est demandé par le navigateur et ce javascript est inclus aussi dans le javascript du formulaire fait qu'elle est générée beaucoup de fois en production. Comme l'erreur inclut tout le contenu du javascript, cela impacte de manière importante la taille des logs côté serveur. Il faut corriger ce comportement, même si cela n'a pas d'impact fonctionnel.

**Comment by lucaa** [comment]
Le même problème est présent sur dev et staging.

**Comment by lucaa** [comment]
@ClemDee je me demandais s'il y a une raison particulière pour laquelle la syntaxe velocity est interprétée dans ce JSX? Il ne semble pas y avoir du code velocity dans ce javascript...

**Comment by lucaa** [comment]
J'ai installé en production la suppression de la configuration de l'interpretation du velocity sur ce javascript.

J'attends la validation de @ClemDee que c'est bien conforme  à l'intention de son code.

**Comment by lucaa** [comment]
Merci pour la confirmation, @ClemDee , je ferme le ticket.

**Comment by ugodtn** [comment]
Ceci est un test (et sera supprimé) @ugodtn.

**Comment by ugodtn** [comment]
Encore un test, bientôt supprimé @ugodtn.

**Comment by ugodtn** [comment]
Ceci est un dernier test @ugodtn.

**Comment by ugodtn** [comment]
Peut-être est-ce enfin le dernier test @ugodtn ?
