### ISSUE TITLE
Limiter le nombre d'avis exportés pour les démarches à forte volumétrie

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1188]
Cette tâche concerne la fonctionnalité d'export des avis d'une démarche, disponible en bas de l'ecran avec la liste des avis d'une démarche.

Initialement cet export était limité à 500 avis, pour des raisons de performance. Ensuite, la fonctionnalité a été refaite et cette limite a été enlevée , voir #882 . 

Par contre, aujourd'hui pour certaines démarches on arrive à la limite de cette nouvelle implémentation aussi.
Ainsi, il faudrait, au moins jusqu'à l'implémentation de #1110 , réinstaurer une limite pour éviter les perturbations de performance du serveur lié à un export fait sur une de ces démarches.

Cette limite sera, évidemment, beaucoup plus élevée que 500 avis, et pourra être différente pour l'export csv vs. export excel. D'ailleurs, pour l'export excel on pourrait tout simplement ne pas proposer l'option si le nombre d'avis est trop élevé.

**Comment by AnthonyBrunelli** [comment]
Il existe trois cas : 
- _moins de 50000 avis_ : rien ne change, fonctionnement actuel
- _de 50000 à 150000 avis_ : l'export Excel n'est pas proposé, seul CSV est proposé. Ajout d'un message : l'export Excel n'est possible qu'avec un maximum de 50.000 avis : utilisez les filtres ci-dessus pour blalbalbal
- _plus de 150000avis_ : l'export Excel n'est pas proposé, seul CSV est proposé _mais uniquement avec les 150.000 premières occurrences_. Ajout d'un message qui explique le cas et quoi faire (filtres).

**Comment by lucaa** [comment]
note: à faire #1097 avec aussi.

**Comment by lucaa** [comment]
Lors de la mise en place du nouveau stockage d'avis et correctif de  #1110 , une limite a été ajoutée pour l'export excel, à 65 000 avis, car le format excel utilisé par l'observatoire a une limite du nombre de lignes à 65535.

Il faudrait vérifier si, avec le nouveau stockage, l'export CSV a encore besoin d'être limité ou pas - des améliorations importantes ont été apportées par #1194 (#1110).

**Comment by lucaa** [comment]
@raphj @ldubost quels sont les résultats de vos tests pour l'export CSV  en terme de temps et mémoire consommée lors d'un export massif (400 000 lignes)?

**Comment by raphj** [comment]
> @raphj @ldubost quels sont les résultats de vos tests pour l'export CSV en terme de temps et mémoire consommée lors d'un export massif (400 000 lignes)?

I just tested 500 000 on perf-staging. It took about 5 minutes for the SQL request to run, about 5 minutes more for the export to run. I don't know about the used memory as I don't have ssh access to the server.

**Comment by raphj** [comment]
J'ai limité l'export CSV à 150 000 lignes comme initialement demandé, ça a l'air d'être une valeur raisonnable. C'est facilement paramétrable.

Voici le rendu (avec des valeurs plus petites pour les tests, je n'ai pas autant d'avis sur ma copie locale de travail) :

https://user-images.githubusercontent.com/3817365/210392337-9bec4531-2702-4cb8-801c-2d36177f50db.mp4

**Comment by lucaa** [comment]
Testé pendant les vacances, l'export des 235 000 avis échoue, avec le même constat que @raphj sur le ralentissement.

**Comment by lucaa** [comment]
Aussi, aujourd'hui il est possible de lancer un export excel pendant qu'un export CSV est déjà en cours (et viceversa) **à partir de la même page**.

Contrairement à ma première impression cela ne lance pas vraiment un deuxième export en parallèle (il y a un message affiché qui annonce qu'un export est en cours et que l'export va être lancé dès que l'autre est fini). Ceci s'applique également à des exports à des avis pour des démarches différentes, sur des pages différentes:
![image](https://user-images.githubusercontent.com/657716/213478704-68bbc8a5-d391-41ac-9dd2-ff3ff086cd93.png)

Ce comportement est correct, il faut le garder.

Par contre, il faut améliorer le cas où ces 2 exports sont lancés depuis la même page:
* dès qu'un des exports est lancé à partir d'une page, et jusqu'à la finalisation de cet export, les boutons d'export devraient être désactivés.

**Comment by lucaa** [comment]
Suite à la mise en place des limites dynamiques par @raphj , il y a une discordance entre les messages affichés: dans la confirmation d'export (lors du click), le comptage réel est utilisé alors que l'export se fait dans les limites posées:

![image](https://user-images.githubusercontent.com/657716/215338053-74e42ed1-34ff-406f-96c0-892e0dc0406d.png)

**Comment by lucaa** [comment]
J'ai simplifié l'implementation de @raphj pour utiliser le paramètre "limit" de la macro livetables exporter.
Ainsi, le problème de warning ci-dessus devient un bug de cette macro : https://jira.xwiki.org/browse/XALTXLS-29 .

**Comment by lucaa** [comment]
le bug a été corrigé dans la version 4.0.1 de l'extension livetable exporter et les instructions de ce projet ont été mises à jour pour noter cette nouvelle version requise.

**Comment by lucaa** [comment]
> Aussi, aujourd'hui il est possible de lancer un export excel pendant qu'un export CSV est déjà en cours (et viceversa) à partir de la même page.
> il faut améliorer le cas où ces 2 exports sont lancés depuis la même page:

Techniquement il est plutôt complexe de détecter cette situation, ainsi, pour l'instant, je ne mets pas en place cette amélioration supplémentaire. On peut étudier le comportement des utilisateurs à l'export suite à la mise en place des limites et revenir sur cette amélioration avec un nouveau ticket, si nécessaire .

**Comment by lucaa** [comment]
Les modifications ont été mises en production.
