### ISSUE TITLE
La création d'un nouvel avis doit utiliser le stockage optimisé des avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1192]
Lié à #1191, cette tâche est pour s'assurer que toute nouvelle création d'avis par le formulaire d'avis stocke correctement l'avis dans le nouveau stockage optimisé.

**Comment by lucaa** [comment]
À priori, par le design des applications XWiki, l'ajout d'un nouvel avis devrait fonctionner après l'implémentation de #1191 sans modification de code.

j'ai fait quelques expérimentations et je n'ai eu aucun problème à l'ajout d'un nouvel avis, je considère cette tâche faite.

@raphj dis-moi si tu penses à d'autres risques ou autre test qu'on devrait faire.

**Comment by raphj** [comment]
Nous avons mis la propriété `<customMapping>` à `internal` dans la classe `AvisClass`, l'avis est bien automatiquement créé dans la nouvelle table `avis`  sans plus de travail nécessaire.

**Comment by lucaa** [comment]
La prise en compte des 2 nouveaux propriétés a été ajouté, mais le résultat fonctionnel fait que la date de l'avis est mise à jour à chaque fois que l'avis est mis à jour (e.g. deuxième étape de l'avis). Je préfère stocker la date de création de l'avis (première étape).

Aussi, du point de vue de l'organisation du code il y a quelques améliorations, c'est pour cette raison que ce ticket reste ouvert, pour l'instant.

**Comment by lucaa** [comment]
>  mais le résultat fonctionnel fait que la date de l'avis est mise à jour à chaque fois que l'avis est mis à jour (e.g. deuxième étape de l'avis). Je préfère stocker la date de création de l'avis (première étape).

en fait, c'est pas le cas, la date et l'id à l'étape de validation sont mises en place uniquement si les valeurs ne sont pas déjà stockées, ce qui fait que la date n'est pas mise à jour.

Il reste à corriger l'endroit ou cette modification a lieu (organisation du code), pour garder le code un peu plus propre.

**Comment by lucaa** [comment]
J'ai mis à jour le code, AvisMacros revient à sa forme initiale, aucune modification n'est nécessaire.

AvisHandler met en place la date de création et le nom de la page dans les méta-données date et id à chaque fois à la première sauvegarde de l'avis (première étape du formulaire).

Si jamais la mise en place n'est pas correcte, les informations sont redondantes, donc peuvent être récupérés à tout moment et re-mises en place.
