### ISSUE TITLE
Refonte de l'affichage des avis détaillés sur la page de la démarche pour utiliser le stockage optimisé des avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1194]
Suite à #1191, le tableau des avis de la page de la démarche n'affichera plus les avis stockés dans le nouveau stockage.

Ainsi, le code qui récupère les avis détaillés pour le tableau devra être refait pour utiliser le nouveau stockage.

Ce changement devrait couvrir d'autres tickets existants de la liste des avis:
* #1110
  *  l'export des avis sera également impacté par ce changement, la performance devrait améliorer considerablement.
* #1004

**Comment by raphj** [comment]
L'affichage de la liste détaillée des avis d'une démarche utilise maintenant une nouvelle requête utilisant le custom mapping en faisant essentiellement select avis from Avis.Code.AvisClass avis where... order by.... Hibernate produit alors une requête SQL complexe qui récupère tous les champs et toutes les lignes nécessaires pour récupérer un avis, et retourne un avis totalement rempli. Les appels à getDocument (y compris les appels à hasRight), produisant des requêtes pour chaque avis, sont maintenant évités.

Nous avons mesuré les performances pour récupérer des centaines de milliers d'avis et cela prend maintenenant quelques dizaines de secondes. Récupérer 50 000 avis prend quelques secondes.

(ps: commentaire initialement rédigé au mauvais endroit, désolé pour le bruit)
