### ISSUE TITLE
Le tri sur les colonnes Activités et Difficultés n'a pas de sens et ne fonctionne pas

### ISSUE THREAD

**Issue by raphj** [DISIC/observatoire#1197]
Il doit donc être désactivé dans les livetables affichant les avis.

**Comment by raphj** [comment]
Ce tri a été désactivé dans la branche add-custom-mapping qui va bientôt être fusionnée.

**Comment by lucaa** [comment]
La branche add-custom-mapping a été fusionnée, la tâche est close.
