### ISSUE TITLE
Harmonisation des paddings des conteneurs avec les paddings du DSFR

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1202]
L'observatoire a des paddings de 15px de chaque côté, le DSFR propose des paddings de 1.5rem (= 24px pour une taille de police de 16px).

Il faut changer les paddings à 24px, principalement pour:
* le header
* le contenu, pour le faire aligner avec le header à gauche pour toutes les pages de largeur 12/12 dans le sens de #1126.

**Comment by ClemDee** [comment]
Les paddings du header et du conteneur ont été harmonisés avec ceux du dsfr.

Modifier la variable bootstrap `@grid-gutter-width` permet de changer la taille des paddings partout sur le wiki. Je n'ai pas remarqué de pages s'afficher bizarrement suite à cette modification, je pense donc que cette solution est viable.
