### ISSUE TITLE
Renommer la plateforme en "L'observatoire de la qualité des services numériques"

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1203]
Remplacer "L’Observatoire de la qualité des démarches en ligne" par "L’observatoire de la qualité des services numériques ", aux endroits suivants:
* logo 
* titre html des pages (titre de la fenetre du navigateur)
* metadata og:title pour les previsualisation d'URL
* phrase explicative dans le footer

**Comment by ClemDee** [comment]
Le titre a été mis à jour aux endroits indiqués, j'ai aussi effectué un grep sur le repo afin d'être certain de pas manquer d'occurrence du titre, et remplacé les quelques autres endroits ou il apparaissait.

**Comment by ClemDee** [comment]
note: la [page Accessibilité](http://observatoire.numerique.devxwiki.com/Main/Accessibilite#HContenusnonaccessibles) contient une référence au titre de la plateforme, mais dans un item d'une liste qui n'est plus d'actualité:
> - Le logo "L'observatoire de la qualité des services numériques" est une image avec du texte incorporé.

Ici j'ai donc retiré cet item de la liste en question.

**Comment by maxime-lecoq** [comment]
Je viens de tester en staging ici : https://observatoire.numerique-staging.devxwiki.com/
- Logo : OK
- Titre html des page : KO - voir PJ
<img width="390" alt="image" src="https://github.com/DISIC/observatoire/assets/82037208/5ef4ec17-e3e4-476a-9a90-252fbe54cfea">
- "metadata og:title pour les previsualisation d'URL" : KO - aucune metadata affichée lorsque je partage l'url. 
- Phrase d'explication dans le footer : OK

**Comment by lucaa** [comment]
> "metadata og:title pour les previsualisation d'URL" : KO - aucune metadata affichée lorsque je partage l'url.

le fait qu'aucune métadata ne s'affiche est probablement normal (mais j'imagine que ça dépend aussi de l'appli ou on essaye la prévisualisation), car le serveur observatoire-staging est _privé, l'accès est protégé par un mot de passe_ (contrairement à la prod). Quand on teste des tels serveurs privés, on donne ce mot de passe à son navigateur.
Les prévisualisation d'URL par les applis impliquent une requête HTTP de l'appli tierce (sur laquelle on partage) vers l'URL à prévisualiser. Si cet URL est privée, il est évident que la requête ne va pas fonctionner car l'appli tierce n'a pas les infos d'accès. 

J'imagine que dans des cas suffisamment rares il se pourrait que si cette appli tierce tourne dans le même navigateur que celui auquel on a donné le mot de passe, en fonction de comment l'application est implémentée, la requête de prévisualisation pourrait passer par le navigateur et pourrait avoir les données d'authentification, mais même dans ce cas là je pense que le système de sécurité du navigateur bloquerait une telle requête car Cross-Origin, donc je doute qu'une telle implémentation de la prévisualisation existe, en fait...

**Comment by lucaa** [comment]
> Titre html des page : KO - voir PJ

@maxime-lecoq si ce test a été fait _sur la page d'accueil non identifiée_ , le problème est sur la nouvelle plateforme, il faut ouvrir un ticket pour la nouvelle plateforme.

Note: j'arrive à reproduire pour la page d'accueil non identifiée, mais pas pour les autres pages et pas pour l'accueil connecté:
Voici l'accueil connecté, tel que je le vois:
![image](https://github.com/DISIC/observatoire/assets/657716/00f2ec95-957e-4842-9577-c7e9b41e8bac)
Et une page de démarche:
![image](https://github.com/DISIC/observatoire/assets/657716/8ce93e88-413c-499d-ab4d-aab9cda3a10e)

**Comment by maxime-lecoq** [comment]
OK pour le titre HTML, c'est chez nous le problème !
