### ISSUE TITLE
Mise à jour de l'image et des metadonnées de partage de la plateforme

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1205]
l'image indiquée par la metadata `og:image` doit être mise à jour.

**Comment by lucaa** [comment]
nouvelle image à fournir par @maxime-lecoq  .

**Comment by maxime-lecoq** [comment]
Référencer les 4 pages suivantes avec des meta données : 

- Page d’accueil :
title : L’Observatoire de la qualité des services publics numériques
description : L’Observatoire recense les services publics numériques les plus utilisés et permet d’analyser, chaque trimestre, leur qualité à travers des critères clés, notamment via les retours directs des usagers.
url : https://observatoire.numerique.gouv.fr/
image : image1

- Page du tableau de suivi :
title : Suivi des services numériques phares de l’État
description : idem page d’accueil
url : https://observatoire.numerique.gouv.fr/observatoire 
image : image1

- Page de description des indicateurs :
title : En savoir plus sur l’Observatoire
description : idem page d’accueil
url : https://observatoire.numerique.gouv.fr/en-savoir-plus 
image : image1

- Page bouton je donne mon avis :
title : Le bouton “Je donne mon avis”
description :  Suivez en temps réel la satisfaction des usagers de vos services publics numériques.
url : https://observatoire.numerique.gouv.fr/je-donne-mon-avis/
image : image2

image1 : Observatoire_de_la_qualité_des_services_publics_numériques
image2 : Bouton_je_donne_mon_avis

![Bouton_je_donne_mon_avis](https://github.com/DISIC/observatoire/assets/82037208/0ac16dfc-fd50-482e-b635-ca418d5d37b3)
![Observatoire_de_la_qualité_des_services_publics_numériques](https://github.com/DISIC/observatoire/assets/82037208/5b1d87bb-bafa-45a7-986b-53ac18ebdd75)

**Comment by maxime-lecoq** [comment]
@lucaa si le temps est un problème, let me know

**Comment by lucaa** [comment]
> @lucaa si le temps est un problème, let me know

C'était pas prévu comme ça mais bon, la différence n'est pas énorme non plus...

**Comment by lucaa** [comment]
Par contre, @maxime-lecoq , il manque un bout de la spécification:
* quelle est l'image et le texte "par défaut", pour toutes les autres pages qui ne sont pas dans la liste des 4 ci-dessus? 
Je suppose que c'est l'image1, "Observatoire_de_la_qualité_des_services_publics_numériques" et le texte 

Aussi, la page de l'observatoire https://observatoire.numerique.gouv.fr/observatoire ainsi que la page d'explication des critères https://observatoire.numerique-staging.devxwiki.com/Aide/Observatoire ne sont plus sur cette plateforme.

Ainsi, je vais re-faire un peu la spec ci-dessus pour qu'elle soit plus complète et adaptée aux fonctionnalités couvertes par cette codebase:
* Par défaut, sur toutes les pages:
  * title : L’Observatoire de la qualité des services publics numériques
  * description : L’Observatoire recense les services publics numériques les plus utilisés et permet d’analyser, chaque trimestre, leur qualité à travers des critères clés, notamment via les retours directs des usagers.
  * image: ![Observatoire_de_la_qualité_des_services_publics_numériques](https://github.com/DISIC/observatoire/assets/82037208/5b1d87bb-bafa-45a7-986b-53ac18ebdd75)
* Avec les exceptions suivantes, qui auront des méta-données spécifiques:
  * Page d'explication du fonctionnement du bouton Je donne mon avis: https://observatoire.numerique.gouv.fr/je-donne-mon-avis/
    * title : Le bouton “Je donne mon avis”
    * description : Suivez en temps réel la satisfaction des usagers de vos services publics numériques.
    * image: ![Bouton_je_donne_mon_avis](https://github.com/DISIC/observatoire/assets/82037208/0ac16dfc-fd50-482e-b635-ca418d5d37b3)
  * Pages des observatoires (top 250), éditions précédentes: tous les URLs de type https://observatoire.numerique.gouv.fr/observatoire/<nom de l'édition ici>, e.g. https://observatoire.numerique.gouv.fr/observatoire/2022-octobre/
    * title : Suivi des services numériques phares de l’État
    * toutes les autres méta-données restent inchangées.
    
Je vais l'implémenter comme ça, mais j'attends la confirmation.

**Comment by lucaa** [comment]
aussi, @maxime-lecoq , je note que le titre "L’Observatoire de la qualité des services publics numériques" est différent du titre prévu pour #1203, c'est normal ou il y aura encore un renommage à faire?

**Comment by lucaa** [comment]
Les modifications telles que décrites ci-dessus sont prêtes à tester en staging.

**Comment by lucaa** [comment]
Suite à un test (sur l'outil de chat Element (Matrix)) et quelques recherches sur internet, il se trouve que Open Graph ne supporte pas les formats .svg d'images. Je n'ai pas trouvé une documentation 'officielle' a ce sujet, malheureusement (je n'ai pas cherché longuement non plus) mais la question était posée par plusieurs sources, et donc, pour être surs, c'est probablement préférable d'utiliser un format plus sûr. 

Ainsi, j'ai exporté les images en format png (en utilisant inkscape), à leur taille d'origine, approx 500:260.

@maxime-lecoq dis-moi s'il y a des modifications à faire. Pour les images, s'il y a des changements, il faudrait fournir les images directement en format final, pour éviter des variations suite à mon export.

**Comment by lucaa** [comment]
> à leur taille d'origine, approx 500:260.

C'est probablement un peu bas, c'est pas clair pourquoi mon outil me propose cette taille pour l'export (car les documents d'origine font ~1886px). @maxime-lecoq j'attends vos directives pour ces images, ça sera probablement plus court...

**Comment by maxime-lecoq** [comment]
Bonjour @lucaa, 
J'ai testé 2 pages "je donne mon avis" et l'accueil connecté, et tout est ok pour moi concernant les meta données.
Voici les images en png.

![Observatoire_de_la_qualité_image](https://github.com/DISIC/observatoire/assets/82037208/42dff748-da1e-48e8-a281-1d5ce29788a3)
![je_donne_mon_avis_image](https://github.com/DISIC/observatoire/assets/82037208/d099e01c-85c7-4fdf-a827-5b39f244be94)
