### ISSUE TITLE
Renommage du lien vers l'observatoire de l'entête

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#1212]
![image](https://github.com/DISIC/observatoire/assets/657716/1120432a-2cdf-44e0-816e-fcfd01aec929)

Nouveau texte: Tableau de suivi des services.

**Comment by lucaa** [comment]
Fait et installé en staging.

**Comment by maxime-lecoq** [comment]
Oui, on ne peut rien te cacher.
Etant donné le moment très tardif de cette mise à jour, c'est OK si la maj
s'effectue plus tard (post MEP) sachant qu'il y aura aussi les images et
les textes des meta données à maj aussi.
Si ça peut vous alléger c'est donc ok de voir ça semaine prochaine.

Maxime
