### ISSUE TITLE
Changement de dernière minute: nom du titre / tableau de service

### ISSUE THREAD

**Issue by ldubost** [DISIC/observatoire#1213]
Par cohérence un changement de dernière minute à été réalisé suite à la mise en production.

1/ Titre du site dans logo / html title / footer

"Vos démarches numériques essentielles"

2/ Dans le top menu "Tableau de suivi"

Les fichiers modifiés sont:

companylogo.vm dans
https://observatoire.numerique.gouv.fr/view/Demarches/Code/WikiDemarchesSkin

et

https://observatoire.numerique.gouv.fr/Demarches/Code/WikiDemarchesTranslations

Ce code doit être commité et vérifié s'il n'y a pas des effets de bords non vus

**Comment by lucaa** [comment]
Cf. les commits de #1203, il y a plein d'autres citations du nom du service, qui sont à traiter lors d'un rennommage, voir https://github.com/DISIC/observatoire/issues/1214#issuecomment-1735627235 .

**Comment by lucaa** [comment]
Les modifications on été committées, il y a quelques effets de bord de ce changement, mais comme il y a un nouveau changement de nom pour #1214 , ils seront traités dans ce ticket-là.
