### ISSUE TITLE
Changement du nom du site de l'observatoire 

### ISSUE THREAD

**Issue by maxime-lecoq** [DISIC/observatoire#1214]
Le ministre a souhaité changer le nom du site. 
On est passé de :
- vos démarches numériques essentielles 
à 
- vos démarches essentielles

Mettre à jour sur l'ensemble des pages observatoire xWiki, connecté et non connecté

**Comment by AnthonyBrunelli** [comment]
'lut ! Aussi, la vignette qui s'affiche lorsqu'on saisit l'URL et la page JDMA :)

**Comment by maxime-lecoq** [comment]
Test sur la page jdma : 

Sur la page je donne mon avis, url : https://observatoire.numerique.gouv.fr/je-donne-mon-avis
titre depuis code source : <meta property="og:title" content="Le bouton “Je donne mon avis”" />
image depuis code source : <meta property="og:image" content="https://observatoire.numerique.gouv.fr/static/observatoire.png" />

**Comment by ClementNumericite** [comment]
L'image a  mettre pour "Vos démarches essentielles"

![observatoire](https://github.com/DISIC/observatoire/assets/80679266/1609d26f-86d1-4c99-8ffb-3f46a06eb224)

**Comment by lucaa** [comment]
Pour tout ce qu'il est méta-données de partage sur les réseaux, un ticket séparé a été créé : #1216 .

**Comment by lucaa** [comment]
Nous avons un petit problème mineur avec ce nom (on avait déjà le problème dès #1213 ): ce nom est utilisé pour afficher le titre du site mais il aparaît également pour designer le site, dans le contexte de quelques messages / pages de documentation. Le nom (d'avant #1213) était "l'observatoire [...]", donc on pouvait l'utiliser normalement dans une phrase comme un nom. Désormais, il s'apelle "vos démarches essentielles" et les phrases doivent changer pour préserver le sens. Il n'est pas clair comment re-faire ces phrases.

Plus précisément, il apparaît dans (les italiques sont pour le but de cette tâche, n'aparaissent pas dans l'utilisation originale):
* la confirmation d'activation de compte: "Votre compte sur l’_Observatoire de la qualité des services numériques_ a bien été activé."
* le dernier écran du formulaire d'avis utilisateurs, dans la phrase "Si cette démarche est suivie dans l’_Observatoire de la qualité des services numériques_, votre note de satisfaction sera prise en compte dans le résultat affiché dans la colonne « Usagers satisfaits »"
* Dans https://observatoire.numerique.gouv.fr/Main/A%20propos , il y a la phrase "En juin 2019, nous avons créé cet _observatoire de la qualité des services numériques_"
* Dans la déclaration d'accessibilité au https://observatoire.numerique.gouv.fr/Main/Accessibilite , il y a 2 phrases:
  * "L’_observatoire de la qualité des services numériques_ est en conformité partielle avec le référentiel général [...]"
  * "Cette déclaration d’accessibilité s’applique à L’_observatoire de la qualité des services numériques_."
* Dans les CGUs au https://observatoire.numerique.gouv.fr/Main/CGU il y a la phrase "L'adresse URL qui permet d'accéder à l'_observatoire de la qualité des services numériques_ est la suivante [...]"

Une reformulation raisonnable que je vois est d'utiliser la formulation "service Vos démarches essentielles" pour remplacer ces usages de l'observatoire [...]. Ainsi, on aura:
* "Votre compte sur le service Vos démarches essentielles a bien été activé."
* "Si cette démarche est suivie dans le service Vos démarches essentielles votre note de satisfaction sera prise en compte dans le résultat affiché dans la colonne « Usagers satisfaits »"
* "En juin 2019, nous avons créé le service Vos démarches essentielles [...]" - cette phrase me parait difficilement reformulable
* "Le service Vos démarches essentielles est en conformité partielle avec le référentiel général [...]"
* "Cette déclaration d’accessibilité s’applique au service Vos démarches essentielles."
* "L'adresse URL qui permet d'accéder au service Vos démarches essentielles est la suivante [...]"

@maxime-lecoq est-ce que tu valides ces reformulations pour toutes ces apparitions supplémentaires du nom?

**Comment by lucaa** [comment]
J'ai également mis à jour d'autres apparitions du mot "observatoire" mais il reste encore des utilisations du terme "observatoire" dans les pages explicatives. Des tickets individuels devraient être crées pour ces apparitions, si elles doivent  être mises à jour.

**Comment by maxime-lecoq** [comment]
Bonjour Anca,
Finalement, tu as appliqué les changements annoncés dans ton premier
commentaire ?
Peux tu confirmer ?
Merci,
Maxime

**Comment by lucaa** [comment]
@maxime-lecoq c'est pas encore en prod car il y a les 2 autres tickets à faire, mais oui, ce sont les changements qui seront deployés en prod dès que cette version est finie.
J'envoie un email quand je mets en prod et cette version sera finie. Aussi, la colonne des tickets va bouger dans le project management ici pour marquer que c'est en prod.

**Comment by maxime-lecoq** [comment]
OK merci.
