### ISSUE TITLE
Footer : changement de l'ordre des liens

### ISSUE THREAD

**Issue by ClementNumericite** [DISIC/observatoire#1215]
Pour des raisons d'accessibilité, l'orde des liens en bas du footer doit être identique sur toutes les pages du site.

Voici ce qu'il y a actuellement coté xWiki
![Capture d’écran du 2023-07-26 15-44-28](https://github.com/DISIC/observatoire/assets/80679266/05264171-0ce5-4992-87a2-9496ce1a2af0)

Voici ce qu'il y a sur le nouveau frontend DSN
![Capture d’écran du 2023-07-26 15-44-41](https://github.com/DISIC/observatoire/assets/80679266/a80f1ef2-0bb6-47df-bdf1-94c045ffa79e)

Il faudrait donc changer l'odre des liens pour qu'il y ait dans cet ordre : 
- Plan du site
- Accessibilité : partiellement conforme
- Mentions légales
- Données personnelles
- Contact
- Code open source

**Comment by lucaa** [comment]
Le lien CGU (premier) ne doit plus exister, c'est le lien Données personnelles qui amène à la page des CGUs, sans ancre.

**Comment by lucaa** [comment]
Done, les liens sont mis à jour tel que décrit ici.
