### ISSUE TITLE
Ajouter du cache pour l'affichage des statistiques des avis d'une démarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/observatoire#866]
Il s'agit d'une amélioration de scalabilité pour le cas de l'accumulation des avis, décrit par #439. 
Les détails pour la page de statistiques sont ici: https://github.com/DISIC/wikidemarches/issues/439#issuecomment-575258158  .

**Comment by AnthonyBrunelli** [comment]
@lucaa Est-ce toujours d'actualité?

**Comment by lucaa** [comment]
@AnthonyBrunelli oui, ça reste toujours à faire. Il s'agit d'une amélioration de la solution provisoire de cache mise en place pour #867 (par exemple, la solution de #867 n'est pas persistente, raison pour laquelle les caches pour les stats aux dates des observatoires doivent être recalculés tous les nuits, alors que ce sont des données qui ne changent pas tous les jours, l'idée est de mettre en place une solution persistente).
 Les travaux à faire sur les écrans de statistiques representent des bonnes occasions de perfectionner ces caches.

**Comment by lucaa** [comment]
Les éléments suivants ont été ajouté:
* un outil de calcul et stockage des données json cachés sur disk pour toutes les démarches ayant un indice de satisfaction supérieur à 0 dans un observatoire donné - les données sont calculés et stockées observatoire par observatoire
  * cet outil a été déjà déployé en production et des caches disk ont commencé à être calculés pour les observatoires, dans l'ordre du plus ancien au plus récent.
* la mise à jour du code d'affichage des graphes d'une démarche pour chercher la donnée sur disk avant de la calculer "en direct" et avant de chercher un indicateur statique.

Cette solution améliore uniquement l'affichage des graphes des démarches à partir des liens dans les observatoires, pour l'affichage des graphes "en direct" la solution est encore le cache HTML en mémoire qui sera pré-calculé tous les matins. Par contre, ce précalcul sera beaucoup plus rapide et léger en terme de charge du serveur, car tous les observatoires n'y feront plus partie (c'était le cas avant ce ticket).

À noter que en ce qui concerne les graphes "en direct" pour une démarche, la solution du cache HTML en mémoire est équivalente à une solution de cache sur disk car le cache HTML a une durée de 24h aujourd'hui (est calculé une fois le matin) et le cache sur disk aurait une même durée de validité (il faudra le re-calculer le lendemain car comme la date change, les données changent). La seule différence c'est pour le cas où il y a un redémarrage dans la journée, dans quel cas le cache HTML en mémoire doit être recalculé alors que le cache sur disk pourra être réutilisé.

Pour l'amélioration du temps de chargement des graphes d'une démarche en direct la solution reste basée sur des agrégats de données tous les jours pour faciliter le calcul des indices des graphes à base des agrégats plutôt que de la donnée brute.

**Comment by AnthonyBrunelli** [comment]
Charge permanente lourde et de plus en plus lourde de calcul des données le matin à partir de 5h pour les graphiques des démarches. Les données des anciens observatoires étant figées, le calcul n'est pas utile: donc précalcul avec cache. Gain de plusieurs heures.
(explication d'Anca en direct)

**Comment by AnthonyBrunelli** [comment]
Déjà en prod.
