### ISSUE TITLE
Dans le header, le logo "L'observatoire de la qualité des démarches en ligne" doit être remplacé par du texte en HTML et CSS.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#952]
Tout est dans le titre

**Comment by AnthonyBrunelli** [comment]
Critère 1.8: Chaque image texte porteuse d’information, en l’absence d’un mécanisme de remplacement, doit si possible être remplacée par du texte stylé. Cette règle est-elle respectée (hors cas particuliers) ?

**Comment by lucaa** [comment]
À explorer avec la mise en place d'un thème plus dsfr dans #1051 .

**Comment by lucaa** [comment]
à noter: dans le style du header DSFR, les intitulés des sites sont en texte aussi.

**Comment by ClemDee** [comment]
L'image a été remplacée par du texte, et les alignements des logos ont été adaptés pour continuer à correspondre aux maquettes.

**Comment by lucaa** [comment]
J'ai vérifié le résultat sur le serveur de dev, il y a une différence de taille des textes entre ce qu'il y avait en image et ce qu'on a en texte:

![image](https://user-images.githubusercontent.com/657716/189625009-ecee9188-a555-491b-861a-18d4e5016bee.png)

aussi, je pense que le titre "l'observatoire de la qualité" est en gras (mais c'est pas sur).

à la limite, la taille exacte au pixel près n'est pas critique, mais il faut préserver les proportions de taille entre le titre et le 'sous-titre'.

**Comment by lucaa** [comment]
suite à un discussion avec @ClemDee , il semble que cette implémentation a été faite pour correspondre aux mockups de 

et c'est dans ces mockups que les tailles ont changé. Néanmoins, j'ai fait une comparaison avec le mockup à hauteur égale d'entête et il reste quelques différences:

![image](https://user-images.githubusercontent.com/657716/189630659-57f91992-d321-4452-87ef-38942d173cd6.png)

* la taille du sous-titre - plus petit sur dev
* espacement entre le titre et le sous-titre qui semble plus élevé sur dev par rapport au moxkup - mais à reverifier une fois la taille corrigée
* j'ai un petit doute sur la taille du titre aussi, elle semble légèrement plus grande sur le mockup. Comme il se peut que le niveau de zoom du mockup de cette capture a une influence sur la taille données par le mockup (police vs hauteur d'entete) et que pour un zoom de 100% la hauteur du header du mockup n'est pas la même sur dev, il faudrait calculer les tailles de polices à mettre en place par rapport au logo Marianne: l'objectif est d'obtenir le même ensemble logo republique francaise + titre que celui du mockup, même si le niveau de 'zoom' pourra être différent.

**Comment by lucaa** [comment]
vu avec @ugodtn en call: le changement des proportions entre les 2 textes n'était pas forcement voulu. 
@ClemDee il faudrait proposer des tailles de texte qui se rapprochent le plus possible de l'image actuelle, surtout au niveau du rapport entre les tailles du titre & sous-titre.

**Comment by ClemDee** [comment]
Le résultat attendu est compliqué à atteindre, car la partie "L'observatoire de la qualité" du logo image est très grasse, et est impossible à reproduire avec la police Marianne fournie et la propriété css `bold`.

J'ai donc fait de mon mieux pour reproduire l'image avec le logo textuel, les tailles est marges devraient être plus proches du résultat attendu mais ce ne sera pas parfait.

J'en ai aussi profité pour corrigé le texte du logo en changeant l'apostrophe anglaise `'` par l'apostrophe française `’`, comme dans l'image originale.

**Comment by AnthonyBrunelli** [comment]
@ugodtn c'est pour oit, au moins en partie! Testable en staging

**Comment by ugodtn** [comment]
C'est très bien !
