### ISSUE TITLE
Page d'accueil Dans la <div id="xwikimainmenu"> l'attribut aria-expanded doit être supprimé.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#953]
J'espère que tout est dans le titre, sinon voir avec Améziane à ajouter en écriture.

**Comment by AnthonyBrunelli** [comment]
Critère 8.2: Pour chaque page web, le code source généré est-il valide selon le type de document spécifié (hors cas particuliers) ?

**Comment by lucaa** [comment]
@AnthonyBrunelli , @amezyane  je n'arrive pas à trouver un tel attribut sur la page d'accueil dans le div en question.
Le markup est:
```<div id="xwikimainmenu" class="collapse navbar-collapse">``` .

En plus, dans l'historique du code, la dernière modification de cette ligne date de #887 , donc cela n'a pas pu être corrigé  entre temps comme un effet de bord d'une autre modification...

Peut-être qu'il s'agit d'un autre élément?

**Comment by ugodtn** [comment]
Vu ensemble, c'est bon.

**Comment by lucaa** [comment]
J'ai clos le ticket car la résolution à l'air d'être, effectivement, "cannot reproduce", et on s'approche de la finalisation de la version 4.10 et ce ticket restait ouvert.
