### ISSUE TITLE
URL du formulaire d'avis : changer voxusagers.numerique.gouv.fr en jedonnemonavis.numerique.gouv.fr

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/observatoire#994]
@ugo tu me donner ton avis là-dessus stp? Des suggestions?

**Comment by lucaa** [comment]
Notes: le changement n'est pas particulièrement compliqué, la partie compliqué, par contre, est la gestion de toutes les intégrations existantes, qui vont continuer à pointer vers voxusagers.numerique.gouv.fr tant que les intégrateurs n'ont pas mis à jour le code du bouton de leur c̛ôté. Ce qui me paraît évident est qu'il faut continuer à accepter tous les URLs vers les formulaires d'avis avec ```voxusagers.numerique.gouv.fr/[...]```, en plus des nouveaux URLs. Ensuite, plusieurs choix sont possibles:
* nous mettons en place des redirections pour rediriger tous les URLs ```voxusagers.numerique.gouv.fr/[...]``` vers les nouvelles URLs, en gardant tous les paramètres. Ainsi, l'utilisateur va voir dans son navigateur, dans la barre d'adresse, la nouvelle URL pour le formulaire de vote.
* nous ne mettons pas en place des redirections, les utilisateurs vont continuer à voir ```voxusagers.numerique.gouv.fr/[...]``` dans la barre d'adresse de leurs navigateurs tant que l’intégrateur n'a pas mis à jour le code du bouton.

**Comment by lucaa** [comment]
Note 2: l'URL du formulaire d'avis ne _doit_ pas être differente de l'URL de l'observatoire, c'était juste un choix de branding qui a été fait lors de #655 / #656 . Il est tout à fait possible de revenir sur ce choix de branding et utiliser le même nom, ```observatoire.numerique.gouv.fr```, la seule différence par rapport à aujourd'hui est que, si on utilise ```observatoire.numerique.gouv.fr``` , il sera désormais possible d’accéder au formulaire d'avis en étant connecté, il faudra tester le comportement du formulaire d'avis et de la page de la démarche (les onglet).

**Comment by AnthonyBrunelli** [comment]
Alors, sur le premier point, je propose la solution "nous mettons en place des redirections pour rediriger tous les URLs voxusagers.numerique.gouv.fr/[...] vers les nouvelles URLs, en gardant tous les paramètres. Ainsi, l'utilisateur va voir dans son navigateur, dans la barre d'adresse, la nouvelle URL pour le formulaire de vote." ce qui nous permet - si je comprends bien - d'être indépendant des "intégrateurs" (parce que ça risque d'être laborieux d'aller leur demander de changer un par un et ça ne sera pas fait partout). @lucaa tu vois un risque particulier? @ugodtn un avis?

Pour la 2ème note, si je comprends bien, il me semble plus prudent pour l'instant de rester sur le même principe qui a prévalu jusque maintenant, surtout que l'on veut faire de JDMA un produit en soit.

Dernier point: cette issue est à traiter indépendamment de la #993 qui est prioritaire, sauf si cela pose problème (auquel cas il faut en discuter).

**Comment by ugodtn** [comment]
@AnthonyBrunelli Je suis clairement pour l'option 1, quand on aura décidé de la nouvelle URL. Et ok pour dire que le changement d'URL peut être décalé, car il nous faudra une validation sur ce point, vu qu'il y a des considérations de marque qui rentrent en jeu (est-ce qu'il faut utiliser la marque Service public + ? ou Observatoire ? ou Je donne mon avis ?). Je trouverais plus logique, personnellement, d'avoir Je donne mon avis dans l'URL, car SV+ c'est bien plus large, et que l'Observatoire ne parle pas à l'usager à ce stade de son parcours.

@lucaa, je ne suis pas certain de comprendre ta note 2 : "il sera désormais possible d’accéder au formulaire d'avis en étant connecté" -> qu'est-ce que ça implique exactement ?

**Comment by AnthonyBrunelli** [comment]
Reste à décider de l'URL à mettre en place donc.

**Comment by lucaa** [comment]
> @lucaa, je ne suis pas certain de comprendre ta note 2 : "il sera désormais possible d’accéder au formulaire d'avis en étant connecté" -> qu'est-ce que ça implique exactement ?

Note: ceci arrive uniquement dans la situation hypothétique ou la même URL observatoire.numerique.gouv.fr est utilisée pour le formulaire d'avis.

Ceci s'appliquera uniquement aux utilisateurs ayant un compte observatoire: administrateurs dinum, administrateurs ministériels et porteurs, pour la scénario suivant: 
* un tel utilisateur se connecte, dans son navigateurs, sur observatoire.numerique.gouv.fr pour faire des opérations de gestion de démarches, 
* l'utilisateur ne se déconnectent pas et ne redémarre pas son navigateur (ferme uniquement l'onglet, par exemple)
* dans le même navigateur et sans le redémarrer, l'utilisateur va faire une démarche administrative, personnelle ou professionnelle, et à la fin de celle ci, il clique le bouton "Je donne mon avis" pour donner son avis
* lors de l'affichage du formulaire d'avis, l'utilisateur sera toujours connecté sur la plateforme, et donc:
  * il verra quelques éléments supplémentaires d'interface (menus, fil d'Ariane, etc) et potentiellement quelques informations supplémentaires sur la démarche (je dois vérifier exactement ce cas, on n'a pas eu la situation depuis longtemps).
  * **surtout,** par le fonctionnement standard de la plateforme, l'avis qu'il laissera sera enregistré comme une modification faite par cet utilisateur connecté, donc **cet avis ne sera pas anonyme**.

**Comment by ugodtn** [comment]
@lucaa ok merci bien noté, je pense que c'est un comportement à éviter du coup. On garde ça en tête, de toute façon on ne va pas statuer tout de suite pour l'URL.

**Comment by AnthonyBrunelli** [comment]
Ayé! On a statué!
- on garde l'option redirection pour passer de vox à la nouvelle URL
- on met les codes des boutons à jour avec la nouvelle URL
- on garde bien valide les anciens URL voxusager (il faut que les utilisateurs qui utilisent le lien voxusager arrivent sur le bon formulaire, même si avec la redirection c'est le nouvel URL qui s'affiche dans le navigateur)
- on remplace la partie de l'URL "voxusager.numerique.gouv.fr" par "observatoire.numerique.gouv.fr"

Reste à voir le problème soulevé du l'utilisateur connecté soulevé plus haut.

J'espère que c'est assez claire. Je laisse @ugodtn arranger ça si besoin :)

**Comment by AnthonyBrunelli** [comment]
Je te l'attribue à nouveau @lucaa - @ugodtn  tu peux toujours réagir si besoin.

**Comment by AnthonyBrunelli** [comment]
Il faudra du coup aussi changer le message d'erreur :
![Capture d’écran 2022-01-06 à 15 34 49](https://user-images.githubusercontent.com/35567048/148404523-5e89f872-45d3-439a-ab4c-dcaedc11d8f0.png)

**Comment by AnthonyBrunelli** [comment]
Pour palier le problème lié à l'identification, nous envisageons de renommer l'URL en:
jedonnemonavis.numerique.gouv.fr
Ok pour @lucaa @ugodtn à faire valider par @marineb et voir avec la autorité compétente (service comm aussi?)
Donc en attente de validation.

NB:  penser à faire une recherche systématique de chaque occurrence de voxusagers à supprimer.

**Comment by marineb** [comment]
Pardon du retard. 
Go de mon côté. On pense que ce sera en prod dans combien de temps ?
Merci beaucoup !!

**Comment by marineb** [comment]
Hello @lucaa ! Ce besoin est urgent, est-ce que tu peux nous dire quand le changement sera en production ? Merci beaucoup. 🙏

**Comment by lucaa** [comment]
@marineb il faudrait créer le sous-domaine ```jedonnemonavis``` sur numerique.gouv.fr qui est de géré du côté Dinum. La mise en place de ce sous-domaine dans le DNS doit être la même que celle pour ```voxusagers``` aujourd'hui (je ne connais pas les details de ce setup pour te dire exactement ce qu'on attend). Je pense que c'est Isaline qui a mis en place les domaines courants, elle poura avoir plus d'informations.

**Comment by lucaa** [comment]
@AnthonyBrunelli de mon côté je commence à tout préparer en attendant (y compris tests) pour ne pas avoir à faire autre chose que le changement de domaine lorsque le domaine sera disponible.

**Comment by lucaa** [comment]
Le code a été mis à jour pour utiliser le nouveau nom dans sa logique multidomaine.

Il reste à élaborer (et à mettre dans les instructions d'installation) les règles de redirection pour garder fonctionnelles tous les URLs des boutons de toutes les démarches où le bouton a été intégré.

@AnthonyBrunelli je pense qu'il faudra prévoir aussi une communication vers les porteurs (on peut la faire sur l'observatoire, si nécessaire) pour les avertir du changement d'URL et qu'il faut qu'ils mettent à jour leurs intégrations.

**Comment by lucaa** [comment]
J'ai élaboré aussi les nouvelles redirections et mis à jour les instructions d'installation ici https://github.com/DISIC/observatoire/wiki/Installation-instructions-v-4.x/44926e3886e38d42e41da6ed220ff6986f3c1bc1#apache-configuration . Je les ai testé sur le serveur de développement.

**Comment by lucaa** [comment]
Je reouvre, il manque la mise à jour du message d'erreur en cas de serveur non-disponible.

**Comment by lucaa** [comment]
Les messages de maintenance sont mises à jour aussi, je ferme le ticket - pas encore installé en staging, mais prêt à installer.

**Comment by lucaa** [comment]
c'est mis aussi en staging, prêt à tester.

**Comment by lucaa** [comment]
testé en staging le 15/04, mis en production le 21/04.

**Comment by AnthonyBrunelli** [comment]
Vu et confirmé en prod, super, merci !
